// Generated by LFG (Let's Fucking Go) — SaaS Autopilot
// 2026-02-27T00:07:12.323Z

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    template: `%s | TeacherHub`,
    default: "TeacherHub",
  },
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100 flex items-center justify-center p-4">
      <div className="w-full max-w-md">
        {/* Logo / App Name */}
        <div className="text-center mb-8">
          <div className="inline-flex items-center justify-center w-12 h-12 rounded-xl bg-indigo-600 mb-4">
            <svg
              className="w-7 h-7 text-white"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M13 10V3L4 14h7v7l9-11h-7z"
              />
            </svg>
          </div>
          <h1 className="text-2xl font-bold text-slate-900">TeacherHub</h1>
          <p className="text-sm text-slate-500 mt-1">A teacher data hub SaaS that connects student data across different school systems like Google Classroom, Clever, PowerSchool, and Canvas. Teachers can create and store document templates shared via Google Drive where they can type freely without constraints. Store information organized by student with unique identifiers. Features include student profiles, document templates, data import from multiple systems, notes per student, report generation, and team collaboration for teaching teams.</p>
        </div>

        {/* Card */}
        <div className="bg-white rounded-2xl shadow-sm border border-slate-200 p-8">
          {children}
        </div>

        {/* Footer */}
        <p className="text-center text-xs text-slate-400 mt-6">
          &copy; {new Date().getFullYear()} TeacherHub. All rights reserved.
        </p>
      </div>
    </div>
  );
}
