// Generated by LFG (Let's Fucking Go) — SaaS Autopilot
// 2026-02-27T00:07:12.321Z

import NextAuth from "next-auth";
import { PrismaAdapter } from "@auth/prisma-adapter";
import type { Adapter } from "next-auth/adapters";
import Credentials from "next-auth/providers/credentials";
import Google from "next-auth/providers/google";
import { db } from "@/lib/db";
import { verifyPassword } from "@/lib/auth-utils";

export const { handlers, auth, signIn, signOut } = NextAuth({
  adapter: PrismaAdapter(db) as Adapter,
  session: {
    strategy: "jwt",
  },
  pages: {
    signIn: "/login",
    newUser: "/signup",
    error: "/login",
  },
  providers: [
    Google({
      clientId: process.env.GOOGLE_CLIENT_ID!,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET!,
    }),
    Credentials({
      name: "credentials",
      credentials: {
        email: { label: "Email", type: "email" },
        password: { label: "Password", type: "password" },
      },
      async authorize(credentials) {
        if (!credentials?.email || !credentials?.password) {
          return null;
        }

        const user = await db.user.findUnique({
          where: { email: credentials.email as string },
          include: {
            memberships: {
              where: { organization: { slug: { not: undefined } } },
              include: { organization: true },
              take: 1,
              orderBy: { createdAt: "asc" },
            },
          },
        });

        if (!user || !user.password) {
          return null;
        }

        const isValid = await verifyPassword(
          credentials.password as string,
          user.password
        );

        if (!isValid) {
          return null;
        }

        return {
          id: user.id,
          email: user.email,
          name: user.name,
          image: user.image,
          role: user.role,
          organizationId: user.memberships[0]?.organizationId ?? null,
        };
      },
    }),
  ],
  callbacks: {
    async jwt({ token, user, trigger, session }) {
      if (user) {
        token.id = user.id;
        token.role = (user as any).role;
        token.organizationId = (user as any).organizationId;
      }

      if (trigger === "update" && session) {
        token.role = session.user?.role ?? token.role;
        token.organizationId =
          session.user?.organizationId ?? token.organizationId;
      }

      return token;
    },
    async session({ session, token }) {
      if (token && session.user) {
        session.user.id = token.id as string;
        session.user.role = token.role as string;
        session.user.organizationId = token.organizationId as string | null;
      }
      return session;
    },
    async signIn({ user, account }) {
      if (account?.provider === "google") {
        // For OAuth sign-ins, ensure the user has an organization
        if (!user.email) return false;

        const existingUser = await db.user.findUnique({
          where: { email: user.email },
          include: { memberships: true },
        });

        if (existingUser && existingUser.memberships.length === 0) {
          // Create a default organization for OAuth users without one
          const orgSlug = user.email
            .split("@")[0]
            .toLowerCase()
            .replace(/[^a-z0-9]/g, "-");

          const org = await db.organization.create({
            data: {
              name: user.name ?? user.email.split("@")[0],
              slug: `${orgSlug}-${Date.now()}`,
            },
          });

          await db.membership.create({
            data: {
              userId: existingUser.id,
              organizationId: org.id,
              role: "OWNER",
            },
          });
        }
      }
      return true;
    },
  },
  events: {
    async createUser({ user }) {
      // Auto-create org for credential sign-up handled in signup action
    },
  },
});
