// Generated by LFG (Let's Fucking Go) — SaaS Autopilot
// 2026-02-27T00:07:12.324Z

import { Resend } from "resend";

const resend = process.env.RESEND_API_KEY
  ? new Resend(process.env.RESEND_API_KEY)
  : null;

const FROM_ADDRESS =
  process.env.EMAIL_FROM ?? "TeacherHub <noreply@teacherhub.com>";

const APP_NAME = "TeacherHub";

function logFallback(to: string, subject: string, html: string) {
  console.log(
    `[EMAIL FALLBACK] To: ${to} | Subject: ${subject}\n${html
      .replace(/<[^>]+>/g, "")
      .trim()
      .slice(0, 300)}`
  );
}

async function sendEmail(to: string, subject: string, html: string) {
  if (!resend) {
    logFallback(to, subject, html);
    return { success: true, fallback: true };
  }

  try {
    const { data, error } = await resend.emails.send({
      from: FROM_ADDRESS,
      to,
      subject,
      html,
    });

    if (error) {
      console.error("Resend error:", error);
      return { success: false, error };
    }

    return { success: true, id: data?.id };
  } catch (err) {
    console.error("Failed to send email:", err);
    logFallback(to, subject, html);
    return { success: false, error: err };
  }
}

function baseTemplate(title: string, body: string) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${title}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { background: #f4f4f5; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; color: #18181b; }
    .wrapper { max-width: 600px; margin: 40px auto; background: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.08); }
    .header { background: linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%); padding: 36px 40px; text-align: center; }
    .header h1 { color: #ffffff; font-size: 22px; font-weight: 700; letter-spacing: -0.3px; }
    .body { padding: 40px; }
    .body p { font-size: 15px; line-height: 1.7; color: #3f3f46; margin-bottom: 20px; }
    .body p:last-child { margin-bottom: 0; }
    .btn { display: inline-block; background: linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%); color: #ffffff !important; text-decoration: none; padding: 13px 28px; border-radius: 8px; font-size: 15px; font-weight: 600; margin: 8px 0 24px; }
    .btn:hover { opacity: 0.9; }
    .divider { border: none; border-top: 1px solid #e4e4e7; margin: 28px 0; }
    .small { font-size: 13px !important; color: #71717a !important; }
    .footer { background: #fafafa; border-top: 1px solid #e4e4e7; padding: 24px 40px; text-align: center; }
    .footer p { font-size: 12px; color: #a1a1aa; line-height: 1.6; }
    .highlight-box { background: #f4f4f5; border-radius: 8px; padding: 20px 24px; margin: 20px 0; }
    .highlight-box p { margin-bottom: 8px; font-size: 14px; }
    .amount { font-size: 32px; font-weight: 700; color: #6366f1; }
  </style>
</head>
<body>
  <div class="wrapper">
    <div class="header">
      <h1>${APP_NAME}</h1>
    </div>
    <div class="body">
      ${body}
    </div>
    <div class="footer">
      <p>You are receiving this email because you have an account with ${APP_NAME}.<br />
      &copy; ${new Date().getFullYear()} ${APP_NAME}. All rights reserved.</p>
    </div>
  </div>
</body>
</html>`;
}

export async function sendWelcomeEmail(to: string, name: string) {
  const firstName = name.split(" ")[0] ?? name;
  const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000";

  const html = baseTemplate(
    `Welcome to ${APP_NAME}!`,
    `
    <p>Hi ${firstName},</p>
    <p>Welcome to <strong>${APP_NAME}</strong> — we're thrilled to have you on board!</p>
    <p>Your account is ready. Click below to get started and explore everything we have to offer.</p>
    <a href="${appUrl}/dashboard" class="btn">Go to Dashboard</a>
    <hr class="divider" />
    <p class="small">If you have any questions, just reply to this email — we're always happy to help.</p>
    `
  );

  return sendEmail(to, `Welcome to ${APP_NAME}!`, html);
}

export async function sendTeamInviteEmail(
  to: string,
  inviterName: string,
  orgName: string,
  inviteUrl: string
) {
  const html = baseTemplate(
    `You've been invited to join ${orgName}`,
    `
    <p>Hi there,</p>
    <p><strong>${inviterName}</strong> has invited you to join <strong>${orgName}</strong> on ${APP_NAME}.</p>
    <p>Click the button below to accept your invitation and get started. This invite link will expire in 7 days.</p>
    <a href="${inviteUrl}" class="btn">Accept Invitation</a>
    <hr class="divider" />
    <p class="small">If you weren't expecting this invitation, you can safely ignore this email. If you have concerns, please contact us.</p>
    <p class="small">Or copy this link: <span style="color:#6366f1;">${inviteUrl}</span></p>
    `
  );

  return sendEmail(
    to,
    `${inviterName} invited you to join ${orgName} on ${APP_NAME}`,
    html
  );
}

export async function sendPasswordResetEmail(to: string, resetUrl: string) {
  const html = baseTemplate(
    "Reset your password",
    `
    <p>Hi there,</p>
    <p>We received a request to reset the password for your ${APP_NAME} account associated with this email address.</p>
    <p>Click the button below to choose a new password. This link will expire in <strong>1 hour</strong>.</p>
    <a href="${resetUrl}" class="btn">Reset Password</a>
    <hr class="divider" />
    <p class="small">If you didn't request a password reset, you can safely ignore this email. Your password will remain unchanged.</p>
    <p class="small">For security, never share this link with anyone.</p>
    `
  );

  return sendEmail(to, `Reset your ${APP_NAME} password`, html);
}

export async function sendPaymentReceiptEmail(
  to: string,
  amount: number,
  planName: string
) {
  const formatted = new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
  }).format(amount / 100);

  const date = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000";

  const html = baseTemplate(
    "Payment receipt",
    `
    <p>Hi there,</p>
    <p>Thank you for your payment — here's your receipt.</p>
    <div class="highlight-box">
      <p class="small" style="text-transform:uppercase;letter-spacing:0.05em;font-weight:600;">Amount paid</p>
      <p class="amount">${formatted}</p>
      <p class="small" style="margin-top:12px;">Plan: <strong>${planName}</strong></p>
      <p class="small">Date: ${date}</p>
    </div>
    <p>Your subscription is active and your account has full access to all ${planName} features.</p>
    <a href="${appUrl}/dashboard/settings/billing" class="btn">View Billing Details</a>
    <hr class="divider" />
    <p class="small">If you have questions about your invoice, reply to this email and we'll be happy to help.</p>
    `
  );

  return sendEmail(to, `Your ${APP_NAME} receipt for ${formatted}`, html);
}
