// Generated by LFG (Let's Fucking Go) — SaaS Autopilot
// 2026-02-27T00:07:12.323Z

import Stripe from "stripe";
import { db } from "@/lib/db";

let _stripe: Stripe | null = null;

export function getStripe(): Stripe {
  if (!_stripe) {
    const key = process.env.STRIPE_SECRET_KEY;
    if (!key) {
      throw new Error("STRIPE_SECRET_KEY is not set. Add it to your .env file.");
    }
    _stripe = new Stripe(key, {
      apiVersion: "2025-02-24.acacia",
      typescript: true,
    });
  }
  return _stripe;
}

export type SubscriptionStatus =
  | "ACTIVE"
  | "TRIALING"
  | "PAST_DUE"
  | "CANCELED"
  | "INCOMPLETE"
  | "INCOMPLETE_EXPIRED"
  | "UNPAID";

export function mapStripeStatus(
  stripeStatus: Stripe.Subscription.Status
): SubscriptionStatus {
  switch (stripeStatus) {
    case "active":
      return "ACTIVE";
    case "trialing":
      return "TRIALING";
    case "past_due":
      return "PAST_DUE";
    case "canceled":
      return "CANCELED";
    case "incomplete":
      return "INCOMPLETE";
    case "incomplete_expired":
      return "INCOMPLETE_EXPIRED";
    case "unpaid":
      return "UNPAID";
    case "paused":
      return "ACTIVE";
    default:
      return "INCOMPLETE";
  }
}

export async function createCheckoutSession(
  organizationId: string,
  priceId: string
): Promise<Stripe.Checkout.Session> {
  const organization = await db.organization.findUnique({
    where: { id: organizationId },
    include: { subscriptions: true },
  });

  if (!organization) {
    throw new Error(`Organization not found: ${organizationId}`);
  }

  let customerId = organization.subscriptions?.[0]?.stripeCustomerId;

  if (!customerId) {
    const customer = await getStripe().customers.create({
      metadata: { organizationId },
    });
    customerId = customer.id;
  }

  const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000";

  const session = await getStripe().checkout.sessions.create({
    customer: customerId,
    payment_method_types: ["card"],
    line_items: [
      {
        price: priceId,
        quantity: 1,
      },
    ],
    mode: "subscription",
    success_url: `${appUrl}/dashboard/settings/billing?success=true`,
    cancel_url: `${appUrl}/dashboard/settings/billing?canceled=true`,
    metadata: { organizationId },
    subscription_data: {
      metadata: { organizationId },
    },
    allow_promotion_codes: true,
  });

  return session;
}

export async function createPortalSession(
  organizationId: string
): Promise<Stripe.BillingPortal.Session> {
  const organization = await db.organization.findUnique({
    where: { id: organizationId },
    include: { subscriptions: true },
  });

  if (!organization) {
    throw new Error(`Organization not found: ${organizationId}`);
  }

  const customerId = organization.subscriptions?.[0]?.stripeCustomerId;

  if (!customerId) {
    throw new Error(
      "No billing account found. Please subscribe to a plan first."
    );
  }

  const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000";

  const session = await getStripe().billingPortal.sessions.create({
    customer: customerId,
    return_url: `${appUrl}/dashboard/settings/billing`,
  });

  return session;
}

export async function getSubscription(organizationId: string) {
  const subscription = await db.subscription.findFirst({
    where: { organizationId },
  });

  if (!subscription) {
    return null;
  }

  if (subscription.stripeSubscriptionId) {
    try {
      const stripeSubscription = await getStripe().subscriptions.retrieve(
        subscription.stripeSubscriptionId,
        { expand: ["default_payment_method", "items.data.price.product"] }
      );
      return { local: subscription, stripe: stripeSubscription };
    } catch {
      return { local: subscription, stripe: null };
    }
  }

  return { local: subscription, stripe: null };
}

export async function cancelSubscription(
  organizationId: string
): Promise<void> {
  const subscription = await db.subscription.findFirst({
    where: { organizationId },
  });

  if (!subscription?.stripeSubscriptionId) {
    throw new Error("No active subscription found");
  }

  await getStripe().subscriptions.update(subscription.stripeSubscriptionId, {
    cancel_at_period_end: true,
  });

  await db.subscription.update({
    where: { id: subscription.id },
    data: { status: "CANCELED" },
  });
}
