// Generated by LFG (Let's Fucking Go) — SaaS Autopilot
// 2026-02-27T00:07:12.323Z

import Stripe from "stripe";
import { db } from "@/lib/db";

if (!process.env.STRIPE_SECRET_KEY) {
  throw new Error("STRIPE_SECRET_KEY environment variable is not set");
}

export const stripe = new Stripe(process.env.STRIPE_SECRET_KEY, {
  apiVersion: "2024-12-18.acacia",
  typescript: true,
});

export type SubscriptionStatus =
  | "active"
  | "trialing"
  | "past_due"
  | "canceled"
  | "incomplete"
  | "incomplete_expired"
  | "unpaid"
  | "paused";

export function mapStripeStatus(
  stripeStatus: Stripe.Subscription.Status
): SubscriptionStatus {
  switch (stripeStatus) {
    case "active":
      return "active";
    case "trialing":
      return "trialing";
    case "past_due":
      return "past_due";
    case "canceled":
      return "canceled";
    case "incomplete":
      return "incomplete";
    case "incomplete_expired":
      return "incomplete_expired";
    case "unpaid":
      return "unpaid";
    case "paused":
      return "paused";
    default:
      return "incomplete";
  }
}

export async function createCheckoutSession(
  organizationId: string,
  priceId: string
): Promise<Stripe.Checkout.Session> {
  const organization = await db.organization.findUnique({
    where: { id: organizationId },
    include: { subscription: true },
  });

  if (!organization) {
    throw new Error(`Organization not found: ${organizationId}`);
  }

  let customerId = organization.subscription?.stripeCustomerId;

  if (!customerId) {
    const customer = await stripe.customers.create({
      metadata: { organizationId },
    });
    customerId = customer.id;
  }

  const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000";

  const session = await stripe.checkout.sessions.create({
    customer: customerId,
    payment_method_types: ["card"],
    line_items: [
      {
        price: priceId,
        quantity: 1,
      },
    ],
    mode: "subscription",
    success_url: `${appUrl}/dashboard/settings/billing?success=true`,
    cancel_url: `${appUrl}/dashboard/settings/billing?canceled=true`,
    metadata: { organizationId },
    subscription_data: {
      metadata: { organizationId },
    },
    allow_promotion_codes: true,
  });

  return session;
}

export async function createPortalSession(
  organizationId: string
): Promise<Stripe.BillingPortal.Session> {
  const organization = await db.organization.findUnique({
    where: { id: organizationId },
    include: { subscription: true },
  });

  if (!organization) {
    throw new Error(`Organization not found: ${organizationId}`);
  }

  const customerId = organization.subscription?.stripeCustomerId;

  if (!customerId) {
    throw new Error(
      "No billing account found. Please subscribe to a plan first."
    );
  }

  const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000";

  const session = await stripe.billingPortal.sessions.create({
    customer: customerId,
    return_url: `${appUrl}/dashboard/settings/billing`,
  });

  return session;
}

export async function getSubscription(organizationId: string) {
  const subscription = await db.subscription.findUnique({
    where: { organizationId },
  });

  if (!subscription) {
    return null;
  }

  if (subscription.stripeSubscriptionId) {
    try {
      const stripeSubscription = await stripe.subscriptions.retrieve(
        subscription.stripeSubscriptionId,
        { expand: ["default_payment_method", "items.data.price.product"] }
      );
      return { local: subscription, stripe: stripeSubscription };
    } catch {
      return { local: subscription, stripe: null };
    }
  }

  return { local: subscription, stripe: null };
}

export async function cancelSubscription(
  organizationId: string
): Promise<void> {
  const subscription = await db.subscription.findUnique({
    where: { organizationId },
  });

  if (!subscription?.stripeSubscriptionId) {
    throw new Error("No active subscription found");
  }

  await stripe.subscriptions.update(subscription.stripeSubscriptionId, {
    cancel_at_period_end: true,
  });

  await db.subscription.update({
    where: { organizationId },
    data: { cancelAtPeriodEnd: true },
  });
}
