// Generated by LFG (Let's Fucking Go) — SaaS Autopilot
// 2026-02-27T00:07:12.356Z

import { auth } from "@/lib/auth";
import { db } from "@/lib/db";
import { redirect, notFound } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, Trash2 } from "lucide-react";
import { updateDocument, deleteDocument } from "@/lib/actions/document";

export const metadata = {
  title: "Edit Document",
};

export default async function EditDocumentPage({
  params,
}: {
  params: { id: string };
}) {
  const session = await auth();
  if (!session?.user) redirect("/login");

  const item = await db.document.findUnique({
    where: { id: params.id },
  });

  if (!item) notFound();

  if ((item as any).organizationId !== session.user.organizationId) {
    notFound();
  }

  return (
    <div className="max-w-xl space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <Link
            href={`/dashboard/documents/${item.id}`}
            className="inline-flex items-center gap-2 text-sm text-slate-500 hover:text-slate-900 transition-colors mb-4"
          >
            <ArrowLeft className="h-4 w-4" />
            Back to detail
          </Link>
          <h1 className="text-2xl font-semibold text-slate-900">Edit Document</h1>
          <p className="mt-1 text-sm text-slate-500">Update the fields below and save.</p>
        </div>
        <form
          action={async () => {
            "use server";
            await deleteDocument(item.id);
          }}
        >
          <button
            type="submit"
            className="inline-flex items-center gap-2 rounded-lg border border-red-200 bg-white px-3 py-2 text-sm font-medium text-red-600 hover:bg-red-50 transition-colors"
            onClick={(e) => {
              if (!confirm("Delete this document? This cannot be undone.")) {
                e.preventDefault();
              }
            }}
          >
            <Trash2 className="h-3.5 w-3.5" />
            Delete
          </button>
        </form>
      </div>

      {/* Form */}
      <div className="rounded-xl border border-slate-200 bg-white overflow-hidden">
        <form action={updateDocument } className="divide-y divide-slate-100">
          <input type="hidden" name="id" value={item.id} />

          <div className="px-6 py-4 space-y-4">
            {/* Title */}
            <div>
              <label
                htmlFor="title"
                className="block text-sm font-medium text-slate-700 mb-1.5"
              >
                Title
              </label>
              <input
                id="title"
                name="title"
                type="text"
                required
                defaultValue={String(item.title ?? "")}
                className="block w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-900 placeholder:text-slate-400 focus:border-slate-400 focus:outline-none focus:ring-2 focus:ring-slate-900/5"
              />
            </div>
            {/* Type */}
            <div>
              <label
                htmlFor="type"
                className="block text-sm font-medium text-slate-700 mb-1.5"
              >
                Type
              </label>
              <select
                id="type"
                name="type"
                required
                defaultValue={String(item.type ?? "pdf")}
                className="block w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-900 focus:border-slate-400 focus:outline-none focus:ring-2 focus:ring-slate-900/5"
              >
                <option value="pdf">Pdf</option>
                <option value="csv">Csv</option>
                <option value="xlsx">Xlsx</option>
                <option value="doc">Doc</option>
              </select>
            </div>
            {/* Url */}
            <div>
              <label
                htmlFor="url"
                className="block text-sm font-medium text-slate-700 mb-1.5"
              >
                Url
              </label>
              <input
                id="url"
                name="url"
                type="text"
                required
                defaultValue={String(item.url ?? "")}
                className="block w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-900 placeholder:text-slate-400 focus:border-slate-400 focus:outline-none focus:ring-2 focus:ring-slate-900/5"
              />
            </div>
            {/* Size */}
            <div>
              <label
                htmlFor="size"
                className="block text-sm font-medium text-slate-700 mb-1.5"
              >
                Size <span className="text-slate-400 font-normal">(optional)</span>
              </label>
              <input
                id="size"
                name="size"
                type="text"
                
                defaultValue={String(item.size ?? "")}
                className="block w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-900 placeholder:text-slate-400 focus:border-slate-400 focus:outline-none focus:ring-2 focus:ring-slate-900/5"
              />
            </div>
          </div>

          {/* Actions */}
          <div className="px-6 py-4 bg-slate-50 flex items-center justify-end gap-3">
            <Link
              href={`/dashboard/documents/${item.id}`}
              className="rounded-lg border border-slate-200 bg-white px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50 transition-colors"
            >
              Cancel
            </Link>
            <button
              type="submit"
              className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-medium text-white hover:bg-slate-700 transition-colors"
            >
              Save changes
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
