// Generated by LFG (Let's Fucking Go) — SaaS Autopilot
// 2026-02-27T00:07:12.336Z

import { auth } from "@/lib/auth";
import { db } from "@/lib/db";
import { redirect, notFound } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, Pencil, Trash2 } from "lucide-react";
import { deleteReport } from "@/lib/actions/report";

export const metadata = {
  title: "Report Detail",
};

export default async function ReportDetailPage({
  params,
}: {
  params: { id: string };
}) {
  const session = await auth();
  if (!session?.user) redirect("/login");

  const item = await db.report.findUnique({
    where: { id: params.id },
  });

  if (!item) notFound();

  // Ensure the item belongs to the user's organization
  if ((item as any).organizationId !== session.user.organizationId) {
    notFound();
  }

  return (
    <div className="max-w-2xl space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <Link
          href="/dashboard/reports"
          className="inline-flex items-center gap-2 text-sm text-slate-500 hover:text-slate-900 transition-colors"
        >
          <ArrowLeft className="h-4 w-4" />
          Back to Reports
        </Link>
        <div className="flex items-center gap-2">
          <Link
            href={`/dashboard/reports/${item.id}/edit`}
            className="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50 transition-colors"
          >
            <Pencil className="h-3.5 w-3.5" />
            Edit
          </Link>
          <form
            action={async () => {
              "use server";
              await deleteReport(item.id);
            }}
          >
            <button
              type="submit"
              className="inline-flex items-center gap-2 rounded-lg border border-red-200 bg-white px-3 py-2 text-sm font-medium text-red-600 hover:bg-red-50 transition-colors"
              onClick={(e) => {
                if (!confirm("Delete this report? This cannot be undone.")) {
                  e.preventDefault();
                }
              }}
            >
              <Trash2 className="h-3.5 w-3.5" />
              Delete
            </button>
          </form>
        </div>
      </div>

      {/* Detail card */}
      <div className="rounded-xl border border-slate-200 bg-white overflow-hidden">
        <div className="px-6 py-4 border-b border-slate-100">
          <h1 className="text-lg font-semibold text-slate-900">
            Report Details
          </h1>
          <p className="text-sm text-slate-400 mt-0.5 font-mono">{item.id}</p>
        </div>
        <dl className="divide-y divide-slate-100">
          <div className="px-6 py-4 grid grid-cols-3 gap-4">
            <dt className="text-sm font-medium text-slate-500">Title</dt>
            <dd className="col-span-2 text-sm text-slate-900">
              {String(item.title ?? "—")}
            </dd>
          </div>
          <div className="px-6 py-4 grid grid-cols-3 gap-4">
            <dt className="text-sm font-medium text-slate-500">Type</dt>
            <dd className="col-span-2 text-sm text-slate-900">
              <span className="inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium bg-slate-100 text-slate-700">
                {String(item.type ?? "—")}
              </span>
            </dd>
          </div>
          <div className="px-6 py-4 grid grid-cols-3 gap-4">
            <dt className="text-sm font-medium text-slate-500">Data</dt>
            <dd className="col-span-2 text-sm text-slate-900">
              {String(item.data ?? "—")}
            </dd>
          </div>
          <div className="px-6 py-4 grid grid-cols-3 gap-4">
            <dt className="text-sm font-medium text-slate-500">GeneratedAt</dt>
            <dd className="col-span-2 text-sm text-slate-900">
              {String(item.generatedAt ?? "—")}
            </dd>
          </div>
        </dl>
      </div>
    </div>
  );
}
