// Generated by LFG (Let's Fucking Go) — SaaS Autopilot
// 2026-02-27T00:07:12.349Z

"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { requireAuth } from "@/lib/auth-utils";

const reportSchema = z.object({
  title: string,
  type: string,
  data: Record&lt;string, unknown&gt;,
  generatedAt: Date,
});

type ReportInput = z.infer<typeof reportSchema>;

export type ActionResult<T = void> =
  | { success: true; data: T }
  | { success: false; error: string; fieldErrors?: Record<string, string[]> };

// createReport — create a new Report from form data
export async function createReport(
  formData: FormData
): Promise<ActionResult<{ id: string }>> {
  const session = await requireAuth();
  if (!session) {
    return { success: false, error: "You must be signed in to perform this action." };
  }

  const raw: Record<string, unknown> = {};
  raw["title"] = formData.get("title") ?? undefined;
  raw["type"] = formData.get("type") ?? undefined;
  raw["data"] = formData.get("data") ?? undefined;
  raw["generatedAt"] = formData.get("generatedAt") ?? undefined;

  const parsed = reportSchema.safeParse(raw);
  if (!parsed.success) {
    return {
      success: false,
      error: "Validation failed. Please check the form fields.",
      fieldErrors: parsed.error.flatten().fieldErrors as Record<string, string[]>,
    };
  }

  try {
    const record = await prisma.report.create({
      data: {
        ...parsed.data,
        organizationId: session.user.organizationId,
      },
    });

    revalidatePath("/report");
    return { success: true, data: { id: record.id } };
  } catch (error) {
    console.error("[CREATE_REPORT]", error);
    return { success: false, error: "Something went wrong. Please try again." };
  }
}

// updateReport — update an existing Report from form data
export async function updateReport(
  id: string,
  formData: FormData
): Promise<ActionResult<{ id: string }>> {
  const session = await requireAuth();
  if (!session) {
    return { success: false, error: "You must be signed in to perform this action." };
  }

  const raw: Record<string, unknown> = {};
  raw["title"] = formData.get("title") ?? undefined;
  raw["type"] = formData.get("type") ?? undefined;
  raw["data"] = formData.get("data") ?? undefined;
  raw["generatedAt"] = formData.get("generatedAt") ?? undefined;

  const parsed = reportSchema.partial().safeParse(raw);
  if (!parsed.success) {
    return {
      success: false,
      error: "Validation failed. Please check the form fields.",
      fieldErrors: parsed.error.flatten().fieldErrors as Record<string, string[]>,
    };
  }

  try {
    const existing = await prisma.report.findUnique({
      where: { id },
    });

    if (!existing) {
      return { success: false, error: "Report not found." };
    }

    if (existing.organizationId !== session.user.organizationId) {
      return { success: false, error: "You do not have permission to update this record." };
    }

    const record = await prisma.report.update({
      where: { id },
      data: parsed.data,
    });

    revalidatePath("/report");
    revalidatePath(`/report/${id}`);
    return { success: true, data: { id: record.id } };
  } catch (error) {
    console.error("[UPDATE_REPORT]", error);
    return { success: false, error: "Something went wrong. Please try again." };
  }
}

// deleteReport — delete a Report and redirect to list
export async function deleteReport(id: string): Promise<never | ActionResult> {
  const session = await requireAuth();
  if (!session) {
    return { success: false, error: "You must be signed in to perform this action." };
  }

  try {
    const existing = await prisma.report.findUnique({
      where: { id },
    });

    if (!existing) {
      return { success: false, error: "Report not found." };
    }

    if (existing.organizationId !== session.user.organizationId) {
      return { success: false, error: "You do not have permission to delete this record." };
    }

    await prisma.report.delete({
      where: { id },
    });
  } catch (error) {
    console.error("[DELETE_REPORT]", error);
    return { success: false, error: "Something went wrong. Please try again." };
  }

  revalidatePath("/report");
  redirect("/report");
}
