// Generated by LFG (Let's Fucking Go) — SaaS Autopilot
// 2026-02-27T00:07:12.340Z

import { auth } from "@/lib/auth";
import { redirect } from "next/navigation";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { createReport } from "@/lib/actions/report";

export const metadata = {
  title: "New Report",
};

export default async function NewReportPage() {
  const session = await auth();
  if (!session?.user) redirect("/login");

  return (
    <div className="max-w-xl space-y-6">
      {/* Header */}
      <div>
        <Link
          href="/dashboard/reports"
          className="inline-flex items-center gap-2 text-sm text-slate-500 hover:text-slate-900 transition-colors mb-4"
        >
          <ArrowLeft className="h-4 w-4" />
          Back to Reports
        </Link>
        <h1 className="text-2xl font-semibold text-slate-900">New Report</h1>
        <p className="mt-1 text-sm text-slate-500">
          Fill in the details to create a new report.
        </p>
      </div>

      {/* Form */}
      <div className="rounded-xl border border-slate-200 bg-white overflow-hidden">
        <form action={createReport } className="divide-y divide-slate-100">
          <div className="px-6 py-4 space-y-4">
            {/* Title */}
            <div>
              <label
                htmlFor="title"
                className="block text-sm font-medium text-slate-700 mb-1.5"
              >
                Title
              </label>
              <input
                id="title"
                name="title"
                type="text"
                required
                
                placeholder="Enter title"
                className="block w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-900 placeholder:text-slate-400 focus:border-slate-400 focus:outline-none focus:ring-2 focus:ring-slate-900/5"
              />
            </div>
            {/* Type */}
            <div>
              <label
                htmlFor="type"
                className="block text-sm font-medium text-slate-700 mb-1.5"
              >
                Type
              </label>
              <select
                id="type"
                name="type"
                required
                defaultValue="summary"
                className="block w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-900 focus:border-slate-400 focus:outline-none focus:ring-2 focus:ring-slate-900/5"
              >
                <option value="summary">Summary</option>
                <option value="detailed">Detailed</option>
                <option value="custom">Custom</option>
              </select>
            </div>
            {/* Data */}
            <div>
              <label
                htmlFor="data"
                className="block text-sm font-medium text-slate-700 mb-1.5"
              >
                Data
              </label>
              <input
                id="data"
                name="data"
                type="text"
                required
                
                placeholder="Enter data"
                className="block w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-900 placeholder:text-slate-400 focus:border-slate-400 focus:outline-none focus:ring-2 focus:ring-slate-900/5"
              />
            </div>
            {/* GeneratedAt */}
            <div>
              <label
                htmlFor="generatedAt"
                className="block text-sm font-medium text-slate-700 mb-1.5"
              >
                GeneratedAt
              </label>
              <input
                id="generatedAt"
                name="generatedAt"
                type="text"
                required
                
                placeholder="Enter generatedat"
                className="block w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-900 placeholder:text-slate-400 focus:border-slate-400 focus:outline-none focus:ring-2 focus:ring-slate-900/5"
              />
            </div>
          </div>

          {/* Actions */}
          <div className="px-6 py-4 bg-slate-50 flex items-center justify-end gap-3">
            <Link
              href="/dashboard/reports"
              className="rounded-lg border border-slate-200 bg-white px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50 transition-colors"
            >
              Cancel
            </Link>
            <button
              type="submit"
              className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-medium text-white hover:bg-slate-700 transition-colors"
            >
              Create Report
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
