// Generated by LFG (Let's Fucking Go) — SaaS Autopilot
// 2026-02-27T00:07:12.332Z

import { auth } from "@/lib/auth";
import { db } from "@/lib/db";
import { redirect } from "next/navigation";
import { inviteMember, removeMember } from "@/lib/actions/team";
import { UserMinus, Mail } from "lucide-react";

const ROLE_LABELS: Record<string, string> = {
  OWNER: "Owner",
  ADMIN: "Admin",
  MEMBER: "Member",
};

const ROLE_STYLES: Record<string, string> = {
  OWNER: "bg-purple-50 text-purple-700 ring-1 ring-purple-200",
  ADMIN: "bg-blue-50 text-blue-700 ring-1 ring-blue-200",
  MEMBER: "bg-slate-100 text-slate-600 ring-1 ring-slate-200",
};

export default async function TeamPage() {
  const session = await auth();
  if (!session?.user) redirect("/login");

  const orgId = session.user.organizationId;
  if (!orgId) redirect("/dashboard");

  const memberships = await db.membership.findMany({
    where: { organizationId: orgId },
    include: { user: true },
    orderBy: { createdAt: "asc" },
  });

  const currentMembership = memberships.find(
    (m) => m.userId === session.user.id
  );
  const isOwnerOrAdmin =
    currentMembership?.role === "OWNER" ||
    currentMembership?.role === "ADMIN";

  return (
    <div className="max-w-2xl space-y-8">
      <div>
        <h1 className="text-2xl font-semibold text-slate-900">Team</h1>
        <p className="mt-1 text-sm text-slate-500">
          Manage your team members and their roles.
        </p>
      </div>

      {/* Member list */}
      <section className="rounded-xl border border-slate-200 bg-white overflow-hidden">
        <div className="px-6 py-4 border-b border-slate-100 flex items-center justify-between">
          <div>
            <h2 className="text-base font-semibold text-slate-900">Members</h2>
            <p className="text-sm text-slate-500 mt-0.5">
              {memberships.length} member{memberships.length !== 1 ? "s" : ""}
            </p>
          </div>
        </div>
        <ul className="divide-y divide-slate-100">
          {memberships.map((membership) => {
            const isCurrentUser = membership.userId === session.user.id;
            const initials = membership.user.name
              ? membership.user.name
                  .split(" ")
                  .map((n) => n[0])
                  .join("")
                  .toUpperCase()
                  .slice(0, 2)
              : membership.user.email?.[0]?.toUpperCase() ?? "U";

            return (
              <li key={membership.id} className="flex items-center justify-between px-6 py-4">
                <div className="flex items-center gap-3">
                  <div className="flex h-9 w-9 items-center justify-center rounded-full bg-slate-100 text-sm font-medium text-slate-600 shrink-0">
                    {initials}
                  </div>
                  <div>
                    <p className="text-sm font-medium text-slate-900">
                      {membership.user.name ?? membership.user.email}
                      {isCurrentUser && (
                        <span className="ml-2 text-xs text-slate-400">(you)</span>
                      )}
                    </p>
                    <p className="text-xs text-slate-400">{membership.user.email}</p>
                  </div>
                </div>
                <div className="flex items-center gap-3">
                  <span
                    className={`inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium ${
                      ROLE_STYLES[membership.role] ?? ROLE_STYLES.MEMBER
                    }`}
                  >
                    {ROLE_LABELS[membership.role] ?? membership.role}
                  </span>
                  {isOwnerOrAdmin && !isCurrentUser && membership.role !== "OWNER" && (
                    <form action={removeMember}>
                      <input type="hidden" name="membershipId" value={membership.id} />
                      <button
                        type="submit"
                        className="flex items-center gap-1 rounded-md px-2 py-1 text-xs text-red-500 hover:bg-red-50 hover:text-red-700 transition-colors"
                        onClick={(e) => {
                          if (!confirm(`Remove ${membership.user.name ?? membership.user.email} from the team?`)) {
                            e.preventDefault();
                          }
                        }}
                      >
                        <UserMinus className="h-3.5 w-3.5" />
                        Remove
                      </button>
                    </form>
                  )}
                </div>
              </li>
            );
          })}
        </ul>
      </section>

      {/* Invite form */}
      {isOwnerOrAdmin && (
        <section className="rounded-xl border border-slate-200 bg-white overflow-hidden">
          <div className="px-6 py-4 border-b border-slate-100">
            <h2 className="text-base font-semibold text-slate-900">Invite member</h2>
            <p className="text-sm text-slate-500 mt-0.5">
              Send an invitation to add someone to your team.
            </p>
          </div>
          <form action={inviteMember} className="px-6 py-4">
            <input type="hidden" name="organizationId" value={orgId} />
            <div className="flex gap-3">
              <div className="flex-1">
                <label htmlFor="email" className="block text-sm font-medium text-slate-700 mb-1.5">
                  Email address
                </label>
                <div className="relative">
                  <Mail className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400" />
                  <input
                    id="email"
                    name="email"
                    type="email"
                    required
                    placeholder="colleague@example.com"
                    className="block w-full rounded-lg border border-slate-200 bg-white pl-9 pr-3 py-2 text-sm text-slate-900 placeholder:text-slate-400 focus:border-slate-400 focus:outline-none focus:ring-2 focus:ring-slate-900/5"
                  />
                </div>
              </div>
              <div>
                <label htmlFor="role" className="block text-sm font-medium text-slate-700 mb-1.5">
                  Role
                </label>
                <select
                  id="role"
                  name="role"
                  defaultValue="MEMBER"
                  className="block rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-900 focus:border-slate-400 focus:outline-none focus:ring-2 focus:ring-slate-900/5"
                >
                  <option value="MEMBER">Member</option>
                  <option value="ADMIN">Admin</option>
                </select>
              </div>
            </div>
            <div className="mt-4 flex justify-end">
              <button
                type="submit"
                className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-medium text-white hover:bg-slate-700 transition-colors"
              >
                Send invite
              </button>
            </div>
          </form>
        </section>
      )}
    </div>
  );
}
