// Generated by LFG (Let's Fucking Go) — SaaS Autopilot

import { PrismaClient } from "@prisma/client";

const db = new PrismaClient();

// Inline password hashing (avoids importing from src/ which uses Next.js path aliases)
const ITERATIONS = 100_000;
const HASH_ALGORITHM = "SHA-256";
const KEY_LENGTH = 32;

async function hashPassword(password: string): Promise<string> {
  const salt = crypto.getRandomValues(new Uint8Array(16));
  const saltBase64 = Buffer.from(salt.buffer).toString("base64");

  const keyMaterial = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(password),
    { name: "PBKDF2" },
    false,
    ["deriveBits"]
  );

  const derivedBits = await crypto.subtle.deriveBits(
    {
      name: "PBKDF2",
      salt,
      iterations: ITERATIONS,
      hash: HASH_ALGORITHM,
    },
    keyMaterial,
    KEY_LENGTH * 8
  );

  const hashBase64 = Buffer.from(derivedBits).toString("base64");
  return `${ITERATIONS}:${saltBase64}:${hashBase64}`;
}

async function main() {
  console.log("Seeding database for TeacherHub...");

  // ---------------------------------------------------------------------------
  // Test user
  // ---------------------------------------------------------------------------
  const hashedPassword = await hashPassword("password123");

  const user = await db.user.upsert({
    where: { email: "admin@example.com" },
    update: {},
    create: {
      name: "Admin User",
      email: "admin@example.com",
      password: hashedPassword,
      role: "ADMIN",
    },
  });

  console.log(`Upserted user: ${user.email}`);

  // ---------------------------------------------------------------------------
  // Test organization
  // ---------------------------------------------------------------------------
  const org = await db.organization.upsert({
    where: { slug: "teacherhub-demo" },
    update: {},
    create: {
      name: "TeacherHub Demo Org",
      slug: "teacherhub-demo",
    },
  });

  console.log(`Upserted organization: ${org.name}`);

  // ---------------------------------------------------------------------------
  // Membership (owner)
  // ---------------------------------------------------------------------------
  await db.membership.upsert({
    where: {
      userId_organizationId: {
        userId: user.id,
        organizationId: org.id,
      },
    },
    update: {},
    create: {
      userId: user.id,
      organizationId: org.id,
      role: "OWNER",
    },
  });

  console.log("Upserted membership (OWNER)");

  // ---------------------------------------------------------------------------
  // Subscription (trialing)
  // ---------------------------------------------------------------------------
  const existingSubscription = await db.subscription.findFirst({
    where: { organizationId: org.id },
  });

  if (!existingSubscription) {
    await db.subscription.create({
      data: {
        organizationId: org.id,
        status: "TRIALING",
        currentPeriodEnd: new Date(Date.now() + 1000 * 60 * 60 * 24 * 14),
      },
    });
    console.log("Created trial subscription");
  }

  // ---------------------------------------------------------------------------
  // Sample entity data
  // ---------------------------------------------------------------------------

  // Report samples
  console.log("Seeding reports...");
  await db.report.createMany({
    skipDuplicates: true,
    data: [
      {
        organizationId: org.id,
        title: "Q1 Student Progress Report",
        type: "PROGRESS",
        data: { students: 32, avgGrade: "B+" },
        generatedAt: new Date(),
      },
      {
        organizationId: org.id,
        title: "Attendance Summary - January",
        type: "ATTENDANCE",
        data: { totalDays: 22, avgAttendance: "94%" },
        generatedAt: new Date(),
      },
    ],
  });

  // Document samples
  console.log("Seeding documents...");
  await db.document.createMany({
    skipDuplicates: true,
    data: [
      {
        organizationId: org.id,
        title: "IEP Template - Standard",
        type: "TEMPLATE",
        url: "https://drive.google.com/example/iep-template",
      },
      {
        organizationId: org.id,
        title: "Parent Communication Letter",
        type: "TEMPLATE",
        url: "https://drive.google.com/example/parent-letter",
      },
    ],
  });

  console.log("Seed complete.");
}

main()
  .then(async () => {
    await db.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await db.$disconnect();
    process.exit(1);
  });
