// Generated by LFG (Let's Fucking Go) — SaaS Autopilot
// 2026-02-27T00:07:12.321Z

import { PrismaClient } from "@prisma/client";
import { hashPassword } from "../src/lib/auth-utils";

const db = new PrismaClient();

async function main() {
  console.log("Seeding database for TeacherHub...");

  // ---------------------------------------------------------------------------
  // Test user
  // ---------------------------------------------------------------------------
  const hashedPassword = await hashPassword("password123");

  const user = await db.user.upsert({
    where: { email: "admin@example.com" },
    update: {},
    create: {
      name: "Admin User",
      email: "admin@example.com",
      password: hashedPassword,
      role: "ADMIN",
    },
  });

  console.log(`Upserted user: ${user.email}`);

  // ---------------------------------------------------------------------------
  // Test organization
  // ---------------------------------------------------------------------------
  const org = await db.organization.upsert({
    where: { slug: "teacherhub-demo" },
    update: {},
    create: {
      name: "TeacherHub Demo Org",
      slug: "teacherhub-demo",
    },
  });

  console.log(`Upserted organization: ${org.name}`);

  // ---------------------------------------------------------------------------
  // Membership (owner)
  // ---------------------------------------------------------------------------
  await db.membership.upsert({
    where: {
      userId_organizationId: {
        userId: user.id,
        organizationId: org.id,
      },
    },
    update: {},
    create: {
      userId: user.id,
      organizationId: org.id,
      role: "OWNER",
    },
  });

  console.log("Upserted membership (OWNER)");

  // ---------------------------------------------------------------------------
  // Subscription (trialing)
  // ---------------------------------------------------------------------------
  const existingSubscription = await db.subscription.findFirst({
    where: { organizationId: org.id },
  });

  if (!existingSubscription) {
    await db.subscription.create({
      data: {
        organizationId: org.id,
        status: "TRIALING",
        currentPeriodEnd: new Date(Date.now() + 1000 * 60 * 60 * 24 * 14), // 14 days
      },
    });
    console.log("Created trial subscription");
  }

  // ---------------------------------------------------------------------------
  // Sample entity data
  // ---------------------------------------------------------------------------

  // Report samples
  console.log("Seeding reports...");
  await db.report.createMany({
    skipDuplicates: true,
    data: [
      {
        organizationId: org.id,
        title: falsefalsefalsefalsefalsefalse,
        type: falsefalsefalsefalsefalsetrue,
        data: falsefalsefalsefalsefalsefalse,
        generatedAt: falsefalsefalsefalsefalsefalse,
      },
      {
        organizationId: org.id,
        title: falsefalsefalsefalsefalsefalse,
        type: falsefalsefalsefalsefalsetrue,
        data: falsefalsefalsefalsefalsefalse,
        generatedAt: falsefalsefalsefalsefalsefalse,
      },
    ],
  });

  // Document samples
  console.log("Seeding documents...");
  await db.document.createMany({
    skipDuplicates: true,
    data: [
      {
        organizationId: org.id,
        title: falsefalsefalsefalsefalsefalse,
        type: falsefalsefalsefalsefalsetrue,
        url: falsefalsefalsefalsefalsefalse,
      },
      {
        organizationId: org.id,
        title: falsefalsefalsefalsefalsefalse,
        type: falsefalsefalsefalsefalsetrue,
        url: falsefalsefalsefalsefalsefalse,
      },
    ],
  });


  console.log("Seed complete.");
}

main()
  .then(async () => {
    await db.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await db.$disconnect();
    process.exit(1);
  });
