// Generated by LFG (Let's Fucking Go) — SaaS Autopilot
// 2026-02-27T00:07:12.363Z

// =============================================================================
// TeacherHub — Shared TypeScript Types
// Generated from spec entities, roles, and billing plans.
// =============================================================================

// ---------------------------------------------------------------------------
// Utility types
// ---------------------------------------------------------------------------

/** Make all properties of T optional recursively */
export type DeepPartial<T> = T extends object
  ? { [K in keyof T]?: DeepPartial<T[K]> }
  : T;

/** Remove null and undefined from T */
export type NonNullable<T> = T extends null | undefined ? never : T;

/** Pagination parameters */
export interface PaginationParams {
  page?: number;
  pageSize?: number;
  cursor?: string;
}

/** Paginated response wrapper */
export interface PaginatedResponse<T> {
  data: T[];
  total: number;
  page: number;
  pageSize: number;
  hasMore: boolean;
}

/** Standard API response */
export type ApiResponse<T> =
  | { success: true; data: T }
  | { success: false; error: string; code?: string };

/** Action result (for Server Actions) */
export type ActionResult<T = void> =
  | { success: true; data: T }
  | { success: false; error: string };

// ---------------------------------------------------------------------------
// Auth / Session
// ---------------------------------------------------------------------------

export interface SessionUser {
  id: string;
  name: string | null;
  email: string;
  image: string | null;
}

export interface AuthSession {
  user: SessionUser;
  expires: string;
}

// ---------------------------------------------------------------------------
// Organization & Membership
// ---------------------------------------------------------------------------

export type OrgRole = 'owner' | 'admin' | 'member';

export interface Organization {
  id: string;
  name: string;
  slug: string;
  logoUrl?: string | null;
  billingPlan: BillingPlanSlug;
  stripeCustomerId?: string | null;
  stripeSubscriptionId?: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface Membership {
  id: string;
  organizationId: string;
  userId: string;
  role: OrgRole;
  createdAt: Date;
}

export interface MembershipWithUser extends Membership {
  user: {
    id: string;
    name: string | null;
    email: string;
    image: string | null;
  };
}

// ---------------------------------------------------------------------------
// Billing
// ---------------------------------------------------------------------------

export type BillingPlanSlug = 'starter' | 'pro' | 'enterprise';
export type BillingInterval = 'month' | 'year';

export interface BillingPlan {
  name: string;
  slug: BillingPlanSlug;
  price: number;
  interval: BillingInterval;
  features: string[];
  limits?: Record<string, number>;
  highlighted: boolean;
}

export const BILLING_PLANS: BillingPlan[] = [
  {
    name: 'Starter',
    slug: 'starter',
    price: 29,
    interval: 'month',
    features: ['Up to 3 team members', 'Basic features'],
    
    highlighted: false,
  },
  {
    name: 'Pro',
    slug: 'pro',
    price: 79,
    interval: 'month',
    features: ['Up to 10 team members', 'All features', 'Priority support'],
    
    highlighted: true,
  },
  {
    name: 'Enterprise',
    slug: 'enterprise',
    price: 199,
    interval: 'month',
    features: ['Unlimited team members', 'All features', 'Dedicated support', 'Custom integrations'],
    
    highlighted: false,
  },
];

// ---------------------------------------------------------------------------
// Entity interfaces (generated from spec)
// ---------------------------------------------------------------------------

// --- Report ---

export interface Report {
  id: string;
  organizationId: string;
  title: string;
  type: string;
  data: Record&lt;string, unknown&gt;;
  generatedAt: Date;
  createdAt: Date;
  updatedAt: Date;
}

/** Input type for creating a Report */
export type CreateReportInput = Omit<Report, 'id' | 'createdAt' | 'updatedAt' | 'organizationId'>;

/** Input type for updating a Report */
export type UpdateReportInput = Partial<CreateReportInput>;

// --- Document ---

export interface Document {
  id: string;
  organizationId: string;
  title: string;
  type: string;
  url: string;
  size?: number | null;
  createdAt: Date;
  updatedAt: Date;
}

/** Input type for creating a Document */
export type CreateDocumentInput = Omit<Document, 'id' | 'createdAt' | 'updatedAt' | 'organizationId'>;

/** Input type for updating a Document */
export type UpdateDocumentInput = Partial<CreateDocumentInput>;


// ---------------------------------------------------------------------------
// Form state helpers
// ---------------------------------------------------------------------------

export interface FormState {
  error?: string;
  success?: boolean;
  message?: string;
}

// ---------------------------------------------------------------------------
// Navigation
// ---------------------------------------------------------------------------

export interface NavItem {
  title: string;
  href: string;
  icon?: React.ComponentType<{ className?: string }>;
  badge?: string | number;
  disabled?: boolean;
  external?: boolean;
  children?: NavItem[];
}

// ---------------------------------------------------------------------------
// Feature flags
// ---------------------------------------------------------------------------

export type FeatureFlag = 'teamManagement' | 'dataImport' | 'analyticsDashboard' | 'templates';

export interface FeatureGates {
  teamManagement: boolean;
  dataImport: boolean;
  analyticsDashboard: boolean;
  templates: boolean;
}
