// Generated by LFG (Let's Fucking Go) — SaaS Autopilot
// 2026-02-27T00:07:12.324Z

import { NextRequest, NextResponse } from "next/server";
import { getCurrentUser } from "@/lib/auth-utils";
import { createPortalSession } from "@/lib/stripe";

export async function POST(_req: NextRequest) {
  try {
    const user = await getCurrentUser();

    if (!user) {
      return NextResponse.json(
        { error: "Unauthorized" },
        { status: 401 }
      );
    }

    if (!user.organizationId) {
      return NextResponse.json(
        { error: "No organization found for this account" },
        { status: 400 }
      );
    }

    const portalSession = await createPortalSession(user.organizationId);

    return NextResponse.json({ url: portalSession.url }, { status: 200 });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Internal server error";
    console.error("Portal session error:", message);
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
