// Generated by LFG (Let's Fucking Go) — SaaS Autopilot
// 2026-02-27T00:07:12.324Z

import { NextRequest, NextResponse } from "next/server";
import Stripe from "stripe";
import { getStripe, mapStripeStatus } from "@/lib/stripe";
import { db } from "@/lib/db";

export const dynamic = "force-dynamic";

async function handleCheckoutSessionCompleted(
  session: Stripe.Checkout.Session
) {
  const organizationId = session.metadata?.organizationId;
  if (!organizationId) {
    console.error("Missing organizationId in checkout session metadata");
    return;
  }

  const stripeSubscription = await getStripe().subscriptions.retrieve(
    session.subscription as string,
    { expand: ["items.data.price.product"] }
  );

  const priceItem = stripeSubscription.items.data[0];
  const priceId = priceItem?.price.id ?? null;
  const planName =
    typeof priceItem?.price.product === "object"
      ? (priceItem.price.product as Stripe.Product).name
      : null;

  const existing = await db.subscription.findFirst({ where: { organizationId } });

  const subscriptionData = {
    stripeCustomerId: session.customer as string,
    stripeSubscriptionId: stripeSubscription.id,
    stripePriceId: priceId,
    status: mapStripeStatus(stripeSubscription.status),
    currentPeriodEnd: new Date(stripeSubscription.current_period_end * 1000),
  };

  if (existing) {
    await db.subscription.update({
      where: { id: existing.id },
      data: subscriptionData,
    });
  } else {
    await db.subscription.create({
      data: { organizationId, ...subscriptionData },
    });
  }
}

async function handleSubscriptionUpdated(
  subscription: Stripe.Subscription
) {
  const organizationId = subscription.metadata?.organizationId;
  if (!organizationId) {
    // Try to find by stripeSubscriptionId
    const existing = await db.subscription.findFirst({
      where: { stripeSubscriptionId: subscription.id },
    });
    if (!existing) {
      console.error("Cannot find organization for subscription:", subscription.id);
      return;
    }
  }

  const priceItem = subscription.items.data[0];
  const priceId = priceItem?.price.id ?? null;

  const whereClause = organizationId
    ? { organizationId }
    : { stripeSubscriptionId: subscription.id };

  await db.subscription.updateMany({
    where: whereClause,
    data: {
      stripePriceId: priceId,
      status: mapStripeStatus(subscription.status),
      currentPeriodEnd: new Date(subscription.current_period_end * 1000),
    },
  });
}

async function handleSubscriptionDeleted(
  subscription: Stripe.Subscription
) {
  const existing = await db.subscription.findFirst({
    where: { stripeSubscriptionId: subscription.id },
  });

  if (!existing) {
    console.warn("Subscription not found for deletion:", subscription.id);
    return;
  }

  await db.subscription.update({
    where: { id: existing.id },
    data: {
      status: "CANCELED",
    },
  });
}

async function handleInvoicePaymentSucceeded(invoice: Stripe.Invoice) {
  if (!invoice.subscription) return;

  const existing = await db.subscription.findFirst({
    where: { stripeSubscriptionId: invoice.subscription as string },
  });

  if (!existing) return;

  await db.subscription.update({
    where: { id: existing.id },
    data: { status: "ACTIVE" },
  });
}

async function handleInvoicePaymentFailed(invoice: Stripe.Invoice) {
  if (!invoice.subscription) return;

  const existing = await db.subscription.findFirst({
    where: { stripeSubscriptionId: invoice.subscription as string },
  });

  if (!existing) return;

  await db.subscription.update({
    where: { id: existing.id },
    data: { status: "PAST_DUE" },
  });
}

export async function POST(req: NextRequest) {
  const body = await req.text();
  const signature = req.headers.get("stripe-signature");

  if (!signature) {
    return NextResponse.json(
      { error: "Missing stripe-signature header" },
      { status: 400 }
    );
  }

  if (!process.env.STRIPE_WEBHOOK_SECRET) {
    console.error("STRIPE_WEBHOOK_SECRET is not set");
    return NextResponse.json(
      { error: "Webhook secret not configured" },
      { status: 500 }
    );
  }

  let event: Stripe.Event;

  try {
    event = getStripe().webhooks.constructEvent(
      body,
      signature,
      process.env.STRIPE_WEBHOOK_SECRET
    );
  } catch (err) {
    const message = err instanceof Error ? err.message : "Unknown error";
    console.error("Webhook signature verification failed:", message);
    return NextResponse.json(
      { error: `Webhook error: ${message}` },
      { status: 400 }
    );
  }

  try {
    switch (event.type) {
      case "checkout.session.completed":
        await handleCheckoutSessionCompleted(
          event.data.object as Stripe.Checkout.Session
        );
        break;

      case "customer.subscription.updated":
        await handleSubscriptionUpdated(
          event.data.object as Stripe.Subscription
        );
        break;

      case "customer.subscription.deleted":
        await handleSubscriptionDeleted(
          event.data.object as Stripe.Subscription
        );
        break;

      case "invoice.payment_succeeded":
        await handleInvoicePaymentSucceeded(
          event.data.object as Stripe.Invoice
        );
        break;

      case "invoice.payment_failed":
        await handleInvoicePaymentFailed(
          event.data.object as Stripe.Invoice
        );
        break;

      default:
        // Unhandled event type — ignore silently
        break;
    }

    return NextResponse.json({ received: true }, { status: 200 });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Unknown error";
    console.error(`Error processing webhook event ${event.type}:`, message);
    return NextResponse.json(
      { error: "Webhook handler failed" },
      { status: 500 }
    );
  }
}
