// Generated by LFG (Let's Fucking Go) — SaaS Autopilot
// 2026-02-27T00:07:12.332Z

import { auth } from "@/lib/auth";
import { db } from "@/lib/db";
import { redirect } from "next/navigation";
import { updateProfile, updateOrganization, deleteAccount } from "@/lib/actions/settings";

export default async function SettingsPage() {
  const session = await auth();
  if (!session?.user) redirect("/login");

  const user = await db.user.findUnique({
    where: { id: session.user.id },
    include: {
      memberships: {
        include: { organization: true },
        take: 1,
        orderBy: { createdAt: "asc" },
      },
    },
  });

  if (!user) redirect("/login");

  const org = user.memberships[0]?.organization;
  const membership = user.memberships[0];

  const currentPlan = "Starter";

  return (
    <div className="max-w-2xl space-y-8">
      <div>
        <h1 className="text-2xl font-semibold text-slate-900">Settings</h1>
        <p className="mt-1 text-sm text-slate-500">
          Manage your account and organization preferences.
        </p>
      </div>

      {/* Profile section */}
      <section className="rounded-xl border border-slate-200 bg-white overflow-hidden">
        <div className="px-6 py-4 border-b border-slate-100">
          <h2 className="text-base font-semibold text-slate-900">Profile</h2>
          <p className="text-sm text-slate-500 mt-0.5">Update your personal information.</p>
        </div>
        <form action={updateProfile} className="px-6 py-4 space-y-4">
          <div>
            <label htmlFor="name" className="block text-sm font-medium text-slate-700 mb-1.5">
              Full name
            </label>
            <input
              id="name"
              name="name"
              type="text"
              defaultValue={user.name ?? ""}
              className="block w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-900 placeholder:text-slate-400 focus:border-slate-400 focus:outline-none focus:ring-2 focus:ring-slate-900/5"
            />
          </div>
          <div>
            <label htmlFor="email" className="block text-sm font-medium text-slate-700 mb-1.5">
              Email address
            </label>
            <input
              id="email"
              name="email"
              type="email"
              defaultValue={user.email ?? ""}
              className="block w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-900 placeholder:text-slate-400 focus:border-slate-400 focus:outline-none focus:ring-2 focus:ring-slate-900/5"
            />
          </div>
          <div className="flex justify-end pt-2">
            <button
              type="submit"
              className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-medium text-white hover:bg-slate-700 transition-colors"
            >
              Save changes
            </button>
          </div>
        </form>
      </section>

      {/* Organization section */}
      {org && (
        <section className="rounded-xl border border-slate-200 bg-white overflow-hidden">
          <div className="px-6 py-4 border-b border-slate-100">
            <h2 className="text-base font-semibold text-slate-900">Organization</h2>
            <p className="text-sm text-slate-500 mt-0.5">Manage your organization settings.</p>
          </div>
          <form action={updateOrganization} className="px-6 py-4 space-y-4">
            <input type="hidden" name="organizationId" value={org.id} />
            <div>
              <label htmlFor="orgName" className="block text-sm font-medium text-slate-700 mb-1.5">
                Organization name
              </label>
              <input
                id="orgName"
                name="name"
                type="text"
                defaultValue={org.name}
                className="block w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-900 placeholder:text-slate-400 focus:border-slate-400 focus:outline-none focus:ring-2 focus:ring-slate-900/5"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-1.5">
                Organization slug
              </label>
              <input
                type="text"
                value={org.slug}
                disabled
                className="block w-full rounded-lg border border-slate-100 bg-slate-50 px-3 py-2 text-sm text-slate-400 cursor-not-allowed"
              />
              <p className="mt-1 text-xs text-slate-400">Slug cannot be changed after creation.</p>
            </div>
            <div className="flex justify-end pt-2">
              <button
                type="submit"
                className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-medium text-white hover:bg-slate-700 transition-colors"
              >
                Save changes
              </button>
            </div>
          </form>
        </section>
      )}

      {/* Billing section */}
      <section className="rounded-xl border border-slate-200 bg-white overflow-hidden">
        <div className="px-6 py-4 border-b border-slate-100">
          <h2 className="text-base font-semibold text-slate-900">Billing</h2>
          <p className="text-sm text-slate-500 mt-0.5">Manage your subscription and billing.</p>
        </div>
        <div className="px-6 py-4">
          <div className="flex items-center justify-between rounded-lg border border-slate-200 p-4">
            <div>
              <p className="text-sm font-medium text-slate-900">Current plan</p>
              <p className="text-sm text-slate-500 mt-0.5">
                Pro — $79/month
              </p>
            </div>
            <a
              href="/api/billing/portal"
              className="rounded-lg border border-slate-200 bg-white px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50 transition-colors"
            >
              Manage subscription
            </a>
          </div>
          <div className="mt-4 grid grid-cols-3 gap-3">
            <div className="rounded-lg border border-slate-200 bg-white p-4">
              <p className="text-sm font-semibold text-slate-900">Starter</p>
              <p className="text-2xl font-bold mt-1 text-slate-900">$29<span className="text-sm font-normal text-slate-400">/month</span></p>
              <ul className="mt-3 space-y-1">
                <li className="text-xs text-slate-500 flex items-center gap-1.5">
                  <span className="h-1 w-1 rounded-full bg-slate-300 shrink-0" />
                  Up to 3 team members
                </li>
                <li className="text-xs text-slate-500 flex items-center gap-1.5">
                  <span className="h-1 w-1 rounded-full bg-slate-300 shrink-0" />
                  Basic features
                </li>
              </ul>
            </div>
            <div className="rounded-lg border border-slate-900 bg-slate-900 text-white p-4">
              <p className="text-sm font-semibold">Pro</p>
              <p className="text-2xl font-bold mt-1">$79<span className="text-sm font-normal text-slate-300">/month</span></p>
              <ul className="mt-3 space-y-1">
                <li className="text-xs text-slate-300 flex items-center gap-1.5">
                  <span className="h-1 w-1 rounded-full bg-slate-400 shrink-0" />
                  Up to 10 team members
                </li>
                <li className="text-xs text-slate-300 flex items-center gap-1.5">
                  <span className="h-1 w-1 rounded-full bg-slate-400 shrink-0" />
                  All features
                </li>
                <li className="text-xs text-slate-300 flex items-center gap-1.5">
                  <span className="h-1 w-1 rounded-full bg-slate-400 shrink-0" />
                  Priority support
                </li>
              </ul>
            </div>
            <div className="rounded-lg border border-slate-200 bg-white p-4">
              <p className="text-sm font-semibold text-slate-900">Enterprise</p>
              <p className="text-2xl font-bold mt-1 text-slate-900">$199<span className="text-sm font-normal text-slate-400">/month</span></p>
              <ul className="mt-3 space-y-1">
                <li className="text-xs text-slate-500 flex items-center gap-1.5">
                  <span className="h-1 w-1 rounded-full bg-slate-300 shrink-0" />
                  Unlimited team members
                </li>
                <li className="text-xs text-slate-500 flex items-center gap-1.5">
                  <span className="h-1 w-1 rounded-full bg-slate-300 shrink-0" />
                  All features
                </li>
                <li className="text-xs text-slate-500 flex items-center gap-1.5">
                  <span className="h-1 w-1 rounded-full bg-slate-300 shrink-0" />
                  Dedicated support
                </li>
                <li className="text-xs text-slate-500 flex items-center gap-1.5">
                  <span className="h-1 w-1 rounded-full bg-slate-300 shrink-0" />
                  Custom integrations
                </li>
              </ul>
            </div>
          </div>
        </div>
      </section>

      {/* Danger zone */}
      <section className="rounded-xl border border-red-200 bg-white overflow-hidden">
        <div className="px-6 py-4 border-b border-red-100">
          <h2 className="text-base font-semibold text-red-700">Danger zone</h2>
          <p className="text-sm text-red-500 mt-0.5">Irreversible and destructive actions.</p>
        </div>
        <div className="px-6 py-4">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm font-medium text-slate-900">Delete account</p>
              <p className="text-xs text-slate-500 mt-0.5">
                Permanently delete your account and all associated data. This cannot be undone.
              </p>
            </div>
            <form action={deleteAccount}>
              <button
                type="submit"
                className="rounded-lg border border-red-200 bg-white px-4 py-2 text-sm font-medium text-red-600 hover:bg-red-50 transition-colors"
                onClick={(e) => {
                  if (!confirm("Are you sure? This action cannot be undone.")) {
                    e.preventDefault();
                  }
                }}
              >
                Delete account
              </button>
            </form>
          </div>
        </div>
      </section>
    </div>
  );
}
