// Generated by LFG (Let's Fucking Go) — SaaS Autopilot
// 2026-02-27T00:07:12.330Z

import { requireAuth } from "@/lib/auth-utils";
import { db } from "@/lib/db";
import Link from "next/link";
import { ArrowRight, Plus } from "lucide-react";

export default async function DashboardPage() {
  const session = await requireAuth();

  const orgId = session.organizationId;

  // Fetch counts for each entity
  const [
    reportsCount,
    documentsCount,
  ] = await Promise.all([
    db.report.count({ where: { organizationId: orgId ?? undefined } }),
    db.document.count({ where: { organizationId: orgId ?? undefined } }),
  ]);

  const stats = [
    {
      name: "Reports",
      value: reportsCount,
      href: "/dashboard/reports",
      description: "Total reports",
    },
    {
      name: "Documents",
      value: documentsCount,
      href: "/dashboard/documents",
      description: "Total documents",
    },
  ];

  return (
    <div className="space-y-8">
      {/* Welcome header */}
      <div>
        <h1 className="text-2xl font-semibold text-slate-900">
          Welcome back, {session.name?.split(" ")[0] ?? "there"}
        </h1>
        <p className="mt-1 text-sm text-slate-500">
          Here&apos;s an overview of your TeacherHub workspace.
        </p>
      </div>

      {/* Stat cards */}
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-2">
        {stats.map((stat) => (
          <Link
            key={stat.name}
            href={stat.href}
            className="group relative overflow-hidden rounded-xl border border-slate-200 bg-white p-6 shadow-sm hover:shadow-md transition-all duration-200"
          >
            <div className="flex items-start justify-between">
              <div>
                <p className="text-sm font-medium text-slate-500">{stat.name}</p>
                <p className="mt-2 text-3xl font-bold text-slate-900">
                  {stat.value.toLocaleString()}
                </p>
                <p className="mt-1 text-xs text-slate-400">{stat.description}</p>
              </div>
              <ArrowRight className="h-4 w-4 text-slate-300 group-hover:text-slate-600 group-hover:translate-x-0.5 transition-all" />
            </div>
          </Link>
        ))}
      </div>

      {/* Quick actions */}
      <div>
        <h2 className="text-base font-semibold text-slate-900 mb-3">Quick actions</h2>
        <div className="flex flex-wrap gap-2">
          <Link
            href="/dashboard/reports/new"
            className="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-4 py-2 text-sm font-medium text-slate-700 shadow-sm hover:bg-slate-50 hover:border-slate-300 transition-colors"
          >
            <Plus className="h-4 w-4" />
            New Report
          </Link>
          <Link
            href="/dashboard/documents/new"
            className="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-4 py-2 text-sm font-medium text-slate-700 shadow-sm hover:bg-slate-50 hover:border-slate-300 transition-colors"
          >
            <Plus className="h-4 w-4" />
            New Document
          </Link>
        </div>
      </div>

      {/* Recent activity placeholder */}
      <div>
        <h2 className="text-base font-semibold text-slate-900 mb-3">Recent activity</h2>
        <div className="rounded-xl border border-slate-200 bg-white divide-y divide-slate-100">
          <div className="px-6 py-10 text-center">
            <p className="text-sm text-slate-400">No recent activity to show.</p>
            <p className="text-xs text-slate-300 mt-1">
              Activity will appear here as your team uses TeacherHub.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
