// Generated by LFG (Let's Fucking Go) — SaaS Autopilot
// 2026-02-27T00:07:12.328Z

"use client";

import { useState } from "react";
import Link from "next/link";
import { CheckCircle2, XCircle, Star, HelpCircle, ArrowRight } from "lucide-react";
import type { Metadata } from "next";

// Note: for static metadata in a client component, export from a separate
// metadata file or convert this to a server component with a client sub-component.

const BILLING_PLANS = [
  {
    name: "Starter",
    slug: "starter",
    monthlyPrice: 29,
    yearlyPrice: Math.round(29 * 10),
    interval: "month" as const,
    features: [
      "Up to 3 team members",
      "Basic features",
    ],
    highlighted: false,
  },
  {
    name: "Pro",
    slug: "pro",
    monthlyPrice: 79,
    yearlyPrice: Math.round(79 * 10),
    interval: "month" as const,
    features: [
      "Up to 10 team members",
      "All features",
      "Priority support",
    ],
    highlighted: true,
  },
  {
    name: "Enterprise",
    slug: "enterprise",
    monthlyPrice: 199,
    yearlyPrice: Math.round(199 * 10),
    interval: "month" as const,
    features: [
      "Unlimited team members",
      "All features",
      "Dedicated support",
      "Custom integrations",
    ],
    highlighted: false,
  },
] as const;

const FAQS = [
  {
    question: "Can I change my plan later?",
    answer:
      "Yes, you can upgrade or downgrade your plan at any time from your billing settings. Changes take effect immediately and you'll be prorated accordingly.",
  },
  {
    question: "Is there a free trial?",
    answer:
      "All plans include a 14-day free trial. No credit card is required to start. You'll only be charged when you decide to continue after the trial.",
  },
  {
    question: "What payment methods do you accept?",
    answer:
      "We accept all major credit and debit cards (Visa, Mastercard, American Express, Discover) via Stripe. We also support bank transfers for annual plans on request.",
  },
  {
    question: "What happens when I cancel?",
    answer:
      "You can cancel at any time. Your access continues until the end of your current billing period. We don't offer refunds for partial periods, but we'll never charge you after you cancel.",
  },
  {
    question: "Do you offer discounts for nonprofits or education?",
    answer:
      "Yes! We offer special pricing for nonprofits, educational institutions, and open-source projects. Reach out to us at billing@teacherhub.com for details.",
  },
  {
    question: "Is my data safe?",
    answer:
      "Absolutely. We use industry-standard encryption (TLS in transit, AES-256 at rest), regular backups, and follow security best practices. Your data is yours — always.",
  },
];

function PricingToggle({
  yearly,
  onChange,
}: {
  yearly: boolean;
  onChange: (v: boolean) => void;
}) {
  return (
    <div className="flex items-center justify-center gap-4">
      <span
        className={`text-sm font-medium transition-colors ${
          !yearly ? "text-zinc-900" : "text-zinc-400"
        }`}
      >
        Monthly
      </span>
      <button
        onClick={() => onChange(!yearly)}
        className={`relative h-7 w-14 rounded-full transition-colors focus:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:ring-offset-2 ${
          yearly ? "bg-indigo-600" : "bg-zinc-200"
        }`}
        aria-pressed={yearly}
        aria-label="Toggle yearly billing"
      >
        <span
          className={`absolute top-0.5 left-0.5 h-6 w-6 rounded-full bg-white shadow-sm transition-transform ${
            yearly ? "translate-x-7" : "translate-x-0"
          }`}
        />
      </button>
      <span
        className={`flex items-center gap-2 text-sm font-medium transition-colors ${
          yearly ? "text-zinc-900" : "text-zinc-400"
        }`}
      >
        Yearly
        <span className="rounded-full bg-emerald-100 px-2 py-0.5 text-xs font-semibold text-emerald-700">
          Save 17%
        </span>
      </span>
    </div>
  );
}

function PricingCard({
  plan,
  yearly,
}: {
  plan: (typeof BILLING_PLANS)[number];
  yearly: boolean;
}) {
  const price = yearly ? plan.yearlyPrice : plan.monthlyPrice;
  const period = yearly ? "yr" : "mo";

  return (
    <div
      className={`relative flex flex-col rounded-2xl border p-8 transition-all hover:shadow-lg ${
        plan.highlighted
          ? "border-indigo-300 bg-gradient-to-b from-indigo-50/70 to-white ring-2 ring-indigo-300/50 shadow-lg shadow-indigo-100/60"
          : "border-zinc-200 bg-white shadow-sm"
      }`}
    >
      {plan.highlighted && (
        <div className="absolute -top-4 left-1/2 -translate-x-1/2">
          <span className="inline-flex items-center gap-1.5 rounded-full bg-gradient-to-r from-indigo-500 to-violet-600 px-4 py-1 text-xs font-semibold text-white shadow-md">
            <Star className="h-3 w-3 fill-current" />
            Most popular
          </span>
        </div>
      )}

      {/* Plan name & price */}
      <div>
        <h2
          className={`text-xl font-bold ${
            plan.highlighted ? "text-indigo-700" : "text-zinc-900"
          }`}
        >
          {plan.name}
        </h2>

        <div className="mt-5 flex items-end gap-1">
          <span className="text-5xl font-extrabold tracking-tight text-zinc-900">
            ${price}
          </span>
          <span className="mb-1.5 text-base text-zinc-400">/{period}</span>
        </div>

        {yearly && (
          <p className="mt-1 text-sm text-zinc-400">
            Billed annually (${plan.monthlyPrice}/mo if billed monthly)
          </p>
        )}
      </div>

      {/* CTA */}
      <div className="mt-8">
        <Link
          href={`/signup?plan=${plan.slug}&billing=${yearly ? "yearly" : "monthly"}`}
          className={`group flex w-full items-center justify-center gap-2 rounded-xl px-6 py-3.5 text-sm font-semibold transition-all ${
            plan.highlighted
              ? "bg-gradient-to-r from-indigo-500 to-violet-600 text-white shadow-md shadow-indigo-200 hover:from-indigo-600 hover:to-violet-700 hover:-translate-y-0.5 hover:shadow-indigo-300"
              : "border border-zinc-200 bg-white text-zinc-700 hover:border-zinc-300 hover:bg-zinc-50"
          }`}
        >
          Get started
          <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-0.5" />
        </Link>
      </div>

      {/* Feature list */}
      <ul className="mt-8 space-y-3.5 border-t border-zinc-100 pt-8">
        {plan.features.map((feature) => (
          <li key={feature} className="flex items-start gap-3">
            <CheckCircle2
              className={`mt-0.5 h-5 w-5 flex-shrink-0 ${
                plan.highlighted ? "text-indigo-500" : "text-emerald-500"
              }`}
            />
            <span className="text-sm text-zinc-600">{feature}</span>
          </li>
        ))}
      </ul>
    </div>
  );
}

function FaqItem({ question, answer }: { question: string; answer: string }) {
  const [open, setOpen] = useState(false);

  return (
    <div className="border-b border-zinc-200 last:border-0">
      <button
        onClick={() => setOpen(!open)}
        className="flex w-full items-center justify-between py-5 text-left"
        aria-expanded={open}
      >
        <span className="pr-8 text-base font-medium text-zinc-900">
          {question}
        </span>
        <HelpCircle
          className={`h-5 w-5 flex-shrink-0 transition-colors ${
            open ? "text-indigo-500" : "text-zinc-400"
          }`}
        />
      </button>
      {open && (
        <div className="pb-5">
          <p className="text-sm leading-relaxed text-zinc-500">{answer}</p>
        </div>
      )}
    </div>
  );
}

export default function PricingPage() {
  const [yearly, setYearly] = useState(false);

  return (
    <div className="bg-white">
      {/* ── Header ─────────────────────────────────────────── */}
      <section className="relative overflow-hidden bg-zinc-50 py-20 sm:py-28">
        <div
          aria-hidden
          className="pointer-events-none absolute inset-0 -z-10"
        >
          <div className="absolute -top-24 left-1/2 h-[400px] w-[700px] -translate-x-1/2 rounded-full bg-indigo-100/50 blur-3xl" />
        </div>

        <div className="mx-auto max-w-3xl px-6 text-center">
          <p className="text-sm font-semibold uppercase tracking-widest text-indigo-600">
            Pricing
          </p>
          <h1 className="mt-3 text-5xl font-extrabold tracking-tight text-zinc-900 sm:text-6xl">
            Plans for every team
          </h1>
          <p className="mt-5 text-lg leading-relaxed text-zinc-500">
            Start free, scale as you grow. No hidden fees, no surprise bills.
          </p>

          <div className="mt-10">
            <PricingToggle yearly={yearly} onChange={setYearly} />
          </div>
        </div>
      </section>

      {/* ── Pricing Cards ──────────────────────────────────── */}
      <section className="py-16 sm:py-20">
        <div className="mx-auto max-w-7xl px-6">
          <div className="mx-auto grid max-w-5xl grid-cols-1 gap-8 lg:grid-cols-3">
            {BILLING_PLANS.map((plan) => (
              <PricingCard key={plan.slug} plan={plan} yearly={yearly} />
            ))}
          </div>

          <p className="mt-10 text-center text-sm text-zinc-400">
            All plans include a 14-day free trial. No credit card required to start.
          </p>
        </div>
      </section>

      {/* ── Feature Comparison ─────────────────────────────── */}
      <section className="border-t border-zinc-100 bg-zinc-50 py-20 sm:py-24">
        <div className="mx-auto max-w-5xl px-6">
          <h2 className="text-center text-3xl font-extrabold tracking-tight text-zinc-900">
            What&apos;s included in every plan
          </h2>

          <div className="mt-12 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {[
              "14-day free trial",
              "Unlimited projects",
              "SSL encryption",
              "Daily backups",
              "Email support",
              "API access",
              "Team collaboration",
              "Custom integrations",
              "Analytics dashboard",
            ].map((item) => (
              <div
                key={item}
                className="flex items-center gap-3 rounded-xl border border-zinc-200 bg-white px-4 py-3 shadow-sm"
              >
                <CheckCircle2 className="h-5 w-5 flex-shrink-0 text-emerald-500" />
                <span className="text-sm font-medium text-zinc-700">{item}</span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── FAQ ────────────────────────────────────────────── */}
      <section className="py-20 sm:py-24">
        <div className="mx-auto max-w-3xl px-6">
          <h2 className="text-center text-3xl font-extrabold tracking-tight text-zinc-900">
            Frequently asked questions
          </h2>
          <p className="mt-4 text-center text-base text-zinc-500">
            Can&apos;t find what you&apos;re looking for?{" "}
            <a
              href="mailto:support@teacherhub.com"
              className="font-medium text-indigo-600 hover:text-indigo-700 underline underline-offset-2"
            >
              Contact our team
            </a>
          </p>

          <div className="mt-12 rounded-2xl border border-zinc-200 bg-white px-6 shadow-sm">
            {FAQS.map((faq) => (
              <FaqItem
                key={faq.question}
                question={faq.question}
                answer={faq.answer}
              />
            ))}
          </div>
        </div>
      </section>

      {/* ── CTA ────────────────────────────────────────────── */}
      <section className="border-t border-zinc-100 bg-gradient-to-br from-indigo-600 to-violet-700 py-20 sm:py-24">
        <div className="mx-auto max-w-3xl px-6 text-center">
          <h2 className="text-4xl font-extrabold tracking-tight text-white">
            Start your free trial today
          </h2>
          <p className="mt-4 text-lg text-indigo-200">
            14 days free. No credit card required. Cancel anytime.
          </p>
          <div className="mt-8 flex flex-col items-center justify-center gap-4 sm:flex-row">
            <Link
              href="/signup"
              className="group inline-flex items-center gap-2 rounded-xl bg-white px-8 py-4 text-base font-semibold text-indigo-700 shadow-xl transition-all hover:-translate-y-0.5 hover:shadow-2xl"
            >
              Get started free
              <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-0.5" />
            </Link>
            <a
              href="mailto:sales@teacherhub.com"
              className="inline-flex items-center gap-2 rounded-xl border border-white/30 px-8 py-4 text-base font-semibold text-white transition-all hover:border-white/50 hover:bg-white/10"
            >
              Talk to sales
            </a>
          </div>
        </div>
      </section>
    </div>
  );
}
