// Generated by LFG (Let's Fucking Go) — SaaS Autopilot
// 2026-02-27T00:07:12.328Z

import type { Metadata } from "next";
import Link from "next/link";
import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "TeacherHub — TeacherHub — A teacher data hub SaaS that connects student",
    template: `%s | TeacherHub`,
  },
  description: "A teacher data hub SaaS that connects student data across different school systems like Google Classroom, Clever, PowerSchool, and Canvas. Teachers can create and store document templates shared via Google Drive where they can type freely without constraints. Store information organized by student with unique identifiers. Features include student profiles, document templates, data import from multiple systems, notes per student, report generation, and team collaboration for teaching teams.",
};

function MarketingHeader() {
  return (
    <header className="sticky top-0 z-50 w-full border-b border-zinc-200/80 bg-white/90 backdrop-blur-md">
      <div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-6">
        {/* Logo */}
        <Link href="/" className="flex items-center gap-2.5">
          <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-gradient-to-br from-indigo-500 to-violet-600 shadow-sm">
            <span className="text-sm font-bold text-white">
              T
            </span>
          </div>
          <span className="text-lg font-bold text-zinc-900 tracking-tight">
            TeacherHub
          </span>
        </Link>

        {/* Nav */}
        <nav className="hidden items-center gap-1 md:flex">
          <Link
            href="/#features"
            className="rounded-lg px-4 py-2 text-sm font-medium text-zinc-600 transition-colors hover:bg-zinc-100 hover:text-zinc-900"
          >
            Features
          </Link>
          <Link
            href="/pricing"
            className="rounded-lg px-4 py-2 text-sm font-medium text-zinc-600 transition-colors hover:bg-zinc-100 hover:text-zinc-900"
          >
            Pricing
          </Link>
        </nav>

        {/* Auth */}
        <div className="flex items-center gap-3">
          <Link
            href="/login"
            className="hidden rounded-lg px-4 py-2 text-sm font-medium text-zinc-600 transition-colors hover:bg-zinc-100 hover:text-zinc-900 sm:block"
          >
            Log in
          </Link>
          <Link
            href="/signup"
            className="rounded-lg bg-gradient-to-r from-indigo-500 to-violet-600 px-4 py-2 text-sm font-semibold text-white shadow-sm transition-all hover:from-indigo-600 hover:to-violet-700 hover:shadow-md"
          >
            Sign up free
          </Link>
        </div>
      </div>
    </header>
  );
}

function MarketingFooter() {
  return (
    <footer className="border-t border-zinc-200 bg-zinc-50">
      <div className="mx-auto max-w-7xl px-6 py-12">
        <div className="grid grid-cols-2 gap-8 md:grid-cols-4">
          {/* Brand */}
          <div className="col-span-2 md:col-span-1">
            <Link href="/" className="flex items-center gap-2.5">
              <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-gradient-to-br from-indigo-500 to-violet-600">
                <span className="text-sm font-bold text-white">
                  T
                </span>
              </div>
              <span className="text-base font-bold text-zinc-900">
                TeacherHub
              </span>
            </Link>
            <p className="mt-3 text-sm leading-relaxed text-zinc-500">
              TeacherHub — A teacher data hub SaaS that connects student
            </p>
          </div>

          {/* Product */}
          <div>
            <h3 className="mb-4 text-sm font-semibold text-zinc-900">Product</h3>
            <ul className="space-y-3">
              <li>
                <Link href="/#features" className="text-sm text-zinc-500 hover:text-zinc-900 transition-colors">
                  Features
                </Link>
              </li>
              <li>
                <Link href="/pricing" className="text-sm text-zinc-500 hover:text-zinc-900 transition-colors">
                  Pricing
                </Link>
              </li>
              <li>
                <Link href="/changelog" className="text-sm text-zinc-500 hover:text-zinc-900 transition-colors">
                  Changelog
                </Link>
              </li>
            </ul>
          </div>

          {/* Company */}
          <div>
            <h3 className="mb-4 text-sm font-semibold text-zinc-900">Company</h3>
            <ul className="space-y-3">
              <li>
                <Link href="/about" className="text-sm text-zinc-500 hover:text-zinc-900 transition-colors">
                  About
                </Link>
              </li>
              <li>
                <Link href="/blog" className="text-sm text-zinc-500 hover:text-zinc-900 transition-colors">
                  Blog
                </Link>
              </li>
              <li>
                <a href="mailto:hello@teacherhub.com" className="text-sm text-zinc-500 hover:text-zinc-900 transition-colors">
                  Contact
                </a>
              </li>
            </ul>
          </div>

          {/* Legal */}
          <div>
            <h3 className="mb-4 text-sm font-semibold text-zinc-900">Legal</h3>
            <ul className="space-y-3">
              <li>
                <Link href="/privacy" className="text-sm text-zinc-500 hover:text-zinc-900 transition-colors">
                  Privacy Policy
                </Link>
              </li>
              <li>
                <Link href="/terms" className="text-sm text-zinc-500 hover:text-zinc-900 transition-colors">
                  Terms of Service
                </Link>
              </li>
            </ul>
          </div>
        </div>

        <div className="mt-12 flex flex-col items-center justify-between gap-4 border-t border-zinc-200 pt-8 sm:flex-row">
          <p className="text-sm text-zinc-400">
            &copy; {new Date().getFullYear()} TeacherHub. All rights reserved.
          </p>
          <p className="text-sm text-zinc-400">
            Built with{" "}
            <span className="font-medium text-zinc-500">LFG</span>
          </p>
        </div>
      </div>
    </footer>
  );
}

export default function MarketingLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <div className="flex min-h-screen flex-col">
          <MarketingHeader />
          <main className="flex-1">{children}</main>
          <MarketingFooter />
        </div>
      </body>
    </html>
  );
}
