// Generated by LFG (Let's Fucking Go) — SaaS Autopilot
// 2026-02-27T00:07:12.327Z

import Link from "next/link";
import {
  ArrowRight,
  CheckCircle2,
  Zap,
  Shield,
  BarChart3,
  Users,
  Globe,
  Lock,
  Star,
  ChevronRight,
} from "lucide-react";

const FEATURE_ICONS: Record<string, React.ComponentType<{ className?: string }>> = {
  default: Zap,
  analytics: BarChart3,
  security: Shield,
  team: Users,
  global: Globe,
  auth: Lock,
};

function getFeatureIcon(featureName: string) {
  const lower = featureName.toLowerCase();
  if (lower.includes("analytic") || lower.includes("report")) return BarChart3;
  if (lower.includes("security") || lower.includes("auth")) return Shield;
  if (lower.includes("team") || lower.includes("member")) return Users;
  if (lower.includes("global") || lower.includes("multi")) return Globe;
  return Zap;
}

export default function HomePage() {
  return (
    <div className="flex flex-col">
      {/* ── Hero ─────────────────────────────────────────────── */}
      <section className="relative overflow-hidden bg-white">
        {/* Background gradient blobs */}
        <div
          aria-hidden
          className="pointer-events-none absolute inset-0 -z-10"
        >
          <div className="absolute -top-40 left-1/2 h-[600px] w-[900px] -translate-x-1/2 rounded-full bg-gradient-to-br from-indigo-100/70 via-violet-100/50 to-pink-100/30 blur-3xl" />
          <div className="absolute -bottom-20 right-0 h-[400px] w-[600px] rounded-full bg-gradient-to-tl from-indigo-50/80 to-violet-50/40 blur-2xl" />
        </div>

        <div className="mx-auto max-w-7xl px-6 py-24 sm:py-32 lg:py-40">
          <div className="mx-auto max-w-3xl text-center">
            {/* Badge */}
            <div className="mb-8 inline-flex items-center gap-2 rounded-full border border-indigo-200/60 bg-indigo-50/80 px-4 py-1.5 text-sm font-medium text-indigo-700">
              <Star className="h-3.5 w-3.5 fill-current" />
              <span>Now in public beta</span>
              <ChevronRight className="h-3.5 w-3.5" />
            </div>

            <h1 className="text-5xl font-extrabold tracking-tight text-zinc-900 sm:text-6xl lg:text-7xl">
              TeacherHub
            </h1>

            <p className="mt-6 text-xl leading-relaxed text-zinc-500 sm:text-2xl">
              TeacherHub — A teacher data hub SaaS that connects student
            </p>

            <p className="mt-4 text-base leading-relaxed text-zinc-400 sm:text-lg">
              A teacher data hub SaaS that connects student data across different school systems like Google Classroom, Clever, PowerSchool, and Canvas. Teachers can create and store document templates shared via Google Drive where they can type freely without constraints. Store information organized by student with unique identifiers. Features include student profiles, document templates, data import from multiple systems, notes per student, report generation, and team collaboration for teaching teams.
            </p>

            {/* CTA buttons */}
            <div className="mt-10 flex flex-col items-center justify-center gap-4 sm:flex-row">
              <Link
                href="/signup"
                className="group inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-indigo-500 to-violet-600 px-7 py-3.5 text-base font-semibold text-white shadow-lg shadow-indigo-200 transition-all hover:from-indigo-600 hover:to-violet-700 hover:shadow-indigo-300 hover:-translate-y-0.5"
              >
                Get started free
                <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-0.5" />
              </Link>
              <Link
                href="/#features"
                className="inline-flex items-center gap-2 rounded-xl border border-zinc-200 bg-white px-7 py-3.5 text-base font-semibold text-zinc-700 shadow-sm transition-all hover:border-zinc-300 hover:bg-zinc-50 hover:shadow"
              >
                See how it works
              </Link>
            </div>

            {/* Social proof */}
            <p className="mt-8 text-sm text-zinc-400">
              No credit card required &middot; Free to get started &middot; Cancel anytime
            </p>
          </div>

          {/* App mockup / decorative */}
          <div className="mx-auto mt-20 max-w-5xl">
            <div className="relative rounded-2xl border border-zinc-200 bg-gradient-to-br from-zinc-50 to-white p-1 shadow-2xl shadow-zinc-200/60">
              <div className="flex items-center gap-1.5 px-4 py-3">
                <div className="h-2.5 w-2.5 rounded-full bg-red-400" />
                <div className="h-2.5 w-2.5 rounded-full bg-amber-400" />
                <div className="h-2.5 w-2.5 rounded-full bg-green-400" />
                <div className="mx-auto h-5 w-48 rounded-md bg-zinc-100" />
              </div>
              <div className="rounded-xl bg-zinc-50 px-6 py-10">
                <div className="grid grid-cols-3 gap-4">
                  {[1, 2, 3].map((i) => (
                    <div
                      key={i}
                      className="rounded-xl border border-zinc-200 bg-white p-4 shadow-sm"
                    >
                      <div className="mb-3 h-8 w-8 rounded-lg bg-indigo-100" />
                      <div className="h-3 w-3/4 rounded-full bg-zinc-200" />
                      <div className="mt-2 h-2 w-1/2 rounded-full bg-zinc-100" />
                    </div>
                  ))}
                </div>
                <div className="mt-4 rounded-xl border border-zinc-200 bg-white p-4 shadow-sm">
                  <div className="flex items-center gap-4">
                    <div className="h-10 w-full rounded-lg bg-zinc-100" />
                    <div className="h-10 w-32 flex-shrink-0 rounded-lg bg-indigo-100" />
                  </div>
                  <div className="mt-4 space-y-2">
                    {[1, 2, 3, 4].map((i) => (
                      <div
                        key={i}
                        className="h-10 rounded-lg bg-zinc-50 border border-zinc-100"
                      />
                    ))}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ── Features ─────────────────────────────────────────── */}
      <section id="features" className="bg-zinc-50 py-24 sm:py-32">
        <div className="mx-auto max-w-7xl px-6">
          <div className="mx-auto max-w-2xl text-center">
            <p className="text-sm font-semibold uppercase tracking-widest text-indigo-600">
              Features
            </p>
            <h2 className="mt-3 text-4xl font-extrabold tracking-tight text-zinc-900 sm:text-5xl">
              Everything you need to succeed
            </h2>
            <p className="mt-4 text-lg text-zinc-500">
              TeacherHub gives your team the tools to move fast without breaking things.
            </p>
          </div>

          <div className="mx-auto mt-16 grid max-w-6xl grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
            <div className="group relative rounded-2xl border border-zinc-200 bg-white p-6 shadow-sm transition-all hover:border-indigo-200 hover:shadow-md">
              <div className="mb-4 inline-flex h-11 w-11 items-center justify-center rounded-xl bg-gradient-to-br from-indigo-50 to-violet-50 ring-1 ring-indigo-100">
                <Zap className="h-5 w-5 text-indigo-600" />
              </div>
              <h3 className="text-base font-semibold text-zinc-900">
                Team Management
              </h3>
              <p className="mt-2 text-sm leading-relaxed text-zinc-500">
                Invite team members and manage roles
              </p>
            </div>
            <div className="group relative rounded-2xl border border-zinc-200 bg-white p-6 shadow-sm transition-all hover:border-indigo-200 hover:shadow-md">
              <div className="mb-4 inline-flex h-11 w-11 items-center justify-center rounded-xl bg-gradient-to-br from-indigo-50 to-violet-50 ring-1 ring-indigo-100">
                <Zap className="h-5 w-5 text-indigo-600" />
              </div>
              <h3 className="text-base font-semibold text-zinc-900">
                Data Import
              </h3>
              <p className="mt-2 text-sm leading-relaxed text-zinc-500">
                Import data from CSV files
              </p>
            </div>
            <div className="group relative rounded-2xl border border-zinc-200 bg-white p-6 shadow-sm transition-all hover:border-indigo-200 hover:shadow-md">
              <div className="mb-4 inline-flex h-11 w-11 items-center justify-center rounded-xl bg-gradient-to-br from-indigo-50 to-violet-50 ring-1 ring-indigo-100">
                <Zap className="h-5 w-5 text-indigo-600" />
              </div>
              <h3 className="text-base font-semibold text-zinc-900">
                Analytics Dashboard
              </h3>
              <p className="mt-2 text-sm leading-relaxed text-zinc-500">
                Visual reports and analytics
              </p>
            </div>
            <div className="group relative rounded-2xl border border-zinc-200 bg-white p-6 shadow-sm transition-all hover:border-indigo-200 hover:shadow-md">
              <div className="mb-4 inline-flex h-11 w-11 items-center justify-center rounded-xl bg-gradient-to-br from-indigo-50 to-violet-50 ring-1 ring-indigo-100">
                <Zap className="h-5 w-5 text-indigo-600" />
              </div>
              <h3 className="text-base font-semibold text-zinc-900">
                Templates
              </h3>
              <p className="mt-2 text-sm leading-relaxed text-zinc-500">
                Pre-built templates for common use cases
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* ── Pricing ──────────────────────────────────────────── */}
      <section id="pricing" className="bg-white py-24 sm:py-32">
        <div className="mx-auto max-w-7xl px-6">
          <div className="mx-auto max-w-2xl text-center">
            <p className="text-sm font-semibold uppercase tracking-widest text-indigo-600">
              Pricing
            </p>
            <h2 className="mt-3 text-4xl font-extrabold tracking-tight text-zinc-900 sm:text-5xl">
              Simple, transparent pricing
            </h2>
            <p className="mt-4 text-lg text-zinc-500">
              Choose the plan that&apos;s right for you. Upgrade or cancel anytime.
            </p>
          </div>

          <div className="mx-auto mt-16 grid max-w-5xl grid-cols-1 gap-8 lg:grid-cols-3">
            <div className={`relative flex flex-col rounded-2xl border p-8 shadow-sm transition-all hover:shadow-md ${false ? "border-indigo-300 bg-gradient-to-b from-indigo-50/60 to-white ring-2 ring-indigo-300/50 shadow-indigo-100" : "border-zinc-200 bg-white"}`}>

              <div>
                <h3 className={`text-lg font-bold ${false ? "text-indigo-700" : "text-zinc-900"}`}>
                  Starter
                </h3>

                <div className="mt-4 flex items-baseline gap-1">
                  <span className="text-5xl font-extrabold tracking-tight text-zinc-900">
                    $29
                  </span>
                  <span className="text-base text-zinc-400">/month</span>
                </div>

                <ul className="mt-8 space-y-3">
                  <li className="flex items-start gap-3">
                    <CheckCircle2 className={`h-5 w-5 flex-shrink-0 mt-0.5 ${false ? "text-indigo-500" : "text-emerald-500"}`} />
                    <span className="text-sm text-zinc-600">Up to 3 team members</span>
                  </li>
                  <li className="flex items-start gap-3">
                    <CheckCircle2 className={`h-5 w-5 flex-shrink-0 mt-0.5 ${false ? "text-indigo-500" : "text-emerald-500"}`} />
                    <span className="text-sm text-zinc-600">Basic features</span>
                  </li>
                </ul>
              </div>

              <div className="mt-8">
                <Link
                  href={`/signup?plan=starter`}
                  className={`block w-full rounded-xl px-6 py-3 text-center text-sm font-semibold transition-all ${
                    false
                      ? "bg-gradient-to-r from-indigo-500 to-violet-600 text-white shadow-md shadow-indigo-200 hover:from-indigo-600 hover:to-violet-700 hover:-translate-y-0.5"
                      : "border border-zinc-200 bg-white text-zinc-700 hover:border-zinc-300 hover:bg-zinc-50"
                  }`}
                >
                  Get started with Starter
                </Link>
              </div>
            </div>
            <div className={`relative flex flex-col rounded-2xl border p-8 shadow-sm transition-all hover:shadow-md ${false ? "border-indigo-300 bg-gradient-to-b from-indigo-50/60 to-white ring-2 ring-indigo-300/50 shadow-indigo-100" : "border-zinc-200 bg-white"}`}>
              <div className="absolute -top-4 left-1/2 -translate-x-1/2">
                <span className="inline-flex items-center gap-1.5 rounded-full bg-gradient-to-r from-indigo-500 to-violet-600 px-4 py-1 text-xs font-semibold text-white shadow">
                  <Star className="h-3 w-3 fill-current" />
                  Most popular
                </span>
              </div>

              <div>
                <h3 className={`text-lg font-bold ${false ? "text-indigo-700" : "text-zinc-900"}`}>
                  Pro
                </h3>

                <div className="mt-4 flex items-baseline gap-1">
                  <span className="text-5xl font-extrabold tracking-tight text-zinc-900">
                    $79
                  </span>
                  <span className="text-base text-zinc-400">/month</span>
                </div>

                <ul className="mt-8 space-y-3">
                  <li className="flex items-start gap-3">
                    <CheckCircle2 className={`h-5 w-5 flex-shrink-0 mt-0.5 ${false ? "text-indigo-500" : "text-emerald-500"}`} />
                    <span className="text-sm text-zinc-600">Up to 10 team members</span>
                  </li>
                  <li className="flex items-start gap-3">
                    <CheckCircle2 className={`h-5 w-5 flex-shrink-0 mt-0.5 ${false ? "text-indigo-500" : "text-emerald-500"}`} />
                    <span className="text-sm text-zinc-600">All features</span>
                  </li>
                  <li className="flex items-start gap-3">
                    <CheckCircle2 className={`h-5 w-5 flex-shrink-0 mt-0.5 ${false ? "text-indigo-500" : "text-emerald-500"}`} />
                    <span className="text-sm text-zinc-600">Priority support</span>
                  </li>
                </ul>
              </div>

              <div className="mt-8">
                <Link
                  href={`/signup?plan=pro`}
                  className={`block w-full rounded-xl px-6 py-3 text-center text-sm font-semibold transition-all ${
                    false
                      ? "bg-gradient-to-r from-indigo-500 to-violet-600 text-white shadow-md shadow-indigo-200 hover:from-indigo-600 hover:to-violet-700 hover:-translate-y-0.5"
                      : "border border-zinc-200 bg-white text-zinc-700 hover:border-zinc-300 hover:bg-zinc-50"
                  }`}
                >
                  Get started with Pro
                </Link>
              </div>
            </div>
            <div className={`relative flex flex-col rounded-2xl border p-8 shadow-sm transition-all hover:shadow-md ${false ? "border-indigo-300 bg-gradient-to-b from-indigo-50/60 to-white ring-2 ring-indigo-300/50 shadow-indigo-100" : "border-zinc-200 bg-white"}`}>

              <div>
                <h3 className={`text-lg font-bold ${false ? "text-indigo-700" : "text-zinc-900"}`}>
                  Enterprise
                </h3>

                <div className="mt-4 flex items-baseline gap-1">
                  <span className="text-5xl font-extrabold tracking-tight text-zinc-900">
                    $199
                  </span>
                  <span className="text-base text-zinc-400">/month</span>
                </div>

                <ul className="mt-8 space-y-3">
                  <li className="flex items-start gap-3">
                    <CheckCircle2 className={`h-5 w-5 flex-shrink-0 mt-0.5 ${false ? "text-indigo-500" : "text-emerald-500"}`} />
                    <span className="text-sm text-zinc-600">Unlimited team members</span>
                  </li>
                  <li className="flex items-start gap-3">
                    <CheckCircle2 className={`h-5 w-5 flex-shrink-0 mt-0.5 ${false ? "text-indigo-500" : "text-emerald-500"}`} />
                    <span className="text-sm text-zinc-600">All features</span>
                  </li>
                  <li className="flex items-start gap-3">
                    <CheckCircle2 className={`h-5 w-5 flex-shrink-0 mt-0.5 ${false ? "text-indigo-500" : "text-emerald-500"}`} />
                    <span className="text-sm text-zinc-600">Dedicated support</span>
                  </li>
                  <li className="flex items-start gap-3">
                    <CheckCircle2 className={`h-5 w-5 flex-shrink-0 mt-0.5 ${false ? "text-indigo-500" : "text-emerald-500"}`} />
                    <span className="text-sm text-zinc-600">Custom integrations</span>
                  </li>
                </ul>
              </div>

              <div className="mt-8">
                <Link
                  href={`/signup?plan=enterprise`}
                  className={`block w-full rounded-xl px-6 py-3 text-center text-sm font-semibold transition-all ${
                    false
                      ? "bg-gradient-to-r from-indigo-500 to-violet-600 text-white shadow-md shadow-indigo-200 hover:from-indigo-600 hover:to-violet-700 hover:-translate-y-0.5"
                      : "border border-zinc-200 bg-white text-zinc-700 hover:border-zinc-300 hover:bg-zinc-50"
                  }`}
                >
                  Get started with Enterprise
                </Link>
              </div>
            </div>
          </div>

          <p className="mt-10 text-center text-sm text-zinc-400">
            All plans include a 14-day free trial. No credit card required.
          </p>
        </div>
      </section>

      {/* ── Final CTA ────────────────────────────────────────── */}
      <section className="relative overflow-hidden bg-gradient-to-br from-indigo-600 via-indigo-700 to-violet-800 py-24 sm:py-32">
        <div
          aria-hidden
          className="pointer-events-none absolute inset-0"
        >
          <div className="absolute -top-32 left-1/2 h-[500px] w-[700px] -translate-x-1/2 rounded-full bg-white/5 blur-3xl" />
          <div className="absolute bottom-0 right-0 h-64 w-64 rounded-full bg-violet-500/20 blur-2xl" />
        </div>

        <div className="relative mx-auto max-w-4xl px-6 text-center">
          <h2 className="text-4xl font-extrabold tracking-tight text-white sm:text-5xl">
            Ready to get started?
          </h2>
          <p className="mx-auto mt-6 max-w-xl text-lg leading-relaxed text-indigo-200">
            Join teams already using TeacherHub to ship faster and grow smarter. It&apos;s free to get started.
          </p>

          <div className="mt-10 flex flex-col items-center justify-center gap-4 sm:flex-row">
            <Link
              href="/signup"
              className="group inline-flex items-center gap-2 rounded-xl bg-white px-8 py-4 text-base font-semibold text-indigo-700 shadow-xl transition-all hover:-translate-y-0.5 hover:shadow-2xl"
            >
              Start for free
              <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-0.5" />
            </Link>
            <Link
              href="/pricing"
              className="inline-flex items-center gap-2 rounded-xl border border-white/30 px-8 py-4 text-base font-semibold text-white transition-all hover:border-white/50 hover:bg-white/10"
            >
              View pricing
            </Link>
          </div>

          <p className="mt-8 text-sm text-indigo-300">
            No credit card required &middot; Free 14-day trial &middot; Cancel anytime
          </p>
        </div>
      </section>
    </div>
  );
}
