// Generated by LFG (Let's Fucking Go) — SaaS Autopilot
// 2026-02-27T00:07:12.360Z

"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { db } from "@/lib/db";
import { requireAuth } from "@/lib/auth-utils";

const documentSchema = z.object({
  title: z.string(),
  type: z.string(),
  url: z.string(),
  size: z.number().optional(),
});

type DocumentInput = z.infer<typeof documentSchema>;

export type ActionResult<T = void> =
  | { success: true; data: T }
  | { success: false; error: string; fieldErrors?: Record<string, string[]> };

// createDocument — create a new Document from form data
export async function createDocument(
  formData: FormData
): Promise<ActionResult<{ id: string }>> {
  const session = await requireAuth();
  if (!session) {
    return { success: false, error: "You must be signed in to perform this action." };
  }

  const raw: Record<string, unknown> = {};
  raw["title"] = formData.get("title") ?? undefined;
  raw["type"] = formData.get("type") ?? undefined;
  raw["url"] = formData.get("url") ?? undefined;
  raw["size"] = formData.get("size") ?? undefined;

  const parsed = documentSchema.safeParse(raw);
  if (!parsed.success) {
    return {
      success: false,
      error: "Validation failed. Please check the form fields.",
      fieldErrors: parsed.error.flatten().fieldErrors as Record<string, string[]>,
    };
  }

  if (!session.organizationId) {
    return { success: false, error: "No organization context." };
  }

  try {
    const record = await db.document.create({
      data: {
        ...parsed.data,
        organizationId: session.organizationId,
      },
    });

    revalidatePath("/document");
    return { success: true, data: { id: record.id } };
  } catch (error) {
    console.error("[CREATE_DOCUMENT]", error);
    return { success: false, error: "Something went wrong. Please try again." };
  }
}

// updateDocument — update an existing Document from form data
export async function updateDocument(
  id: string,
  formData: FormData
): Promise<ActionResult<{ id: string }>> {
  const session = await requireAuth();
  if (!session) {
    return { success: false, error: "You must be signed in to perform this action." };
  }

  const raw: Record<string, unknown> = {};
  raw["title"] = formData.get("title") ?? undefined;
  raw["type"] = formData.get("type") ?? undefined;
  raw["url"] = formData.get("url") ?? undefined;
  raw["size"] = formData.get("size") ?? undefined;

  const parsed = documentSchema.partial().safeParse(raw);
  if (!parsed.success) {
    return {
      success: false,
      error: "Validation failed. Please check the form fields.",
      fieldErrors: parsed.error.flatten().fieldErrors as Record<string, string[]>,
    };
  }

  try {
    const existing = await db.document.findUnique({
      where: { id },
    });

    if (!existing) {
      return { success: false, error: "Document not found." };
    }

    if (existing.organizationId !== session.organizationId) {
      return { success: false, error: "You do not have permission to update this record." };
    }

    const record = await db.document.update({
      where: { id },
      data: parsed.data,
    });

    revalidatePath("/document");
    revalidatePath(`/document/${id}`);
    return { success: true, data: { id: record.id } };
  } catch (error) {
    console.error("[UPDATE_DOCUMENT]", error);
    return { success: false, error: "Something went wrong. Please try again." };
  }
}

// deleteDocument — delete a Document and redirect to list
export async function deleteDocument(id: string): Promise<never | ActionResult> {
  const session = await requireAuth();
  if (!session) {
    return { success: false, error: "You must be signed in to perform this action." };
  }

  try {
    const existing = await db.document.findUnique({
      where: { id },
    });

    if (!existing) {
      return { success: false, error: "Document not found." };
    }

    if (existing.organizationId !== session.organizationId) {
      return { success: false, error: "You do not have permission to delete this record." };
    }

    await db.document.delete({
      where: { id },
    });
  } catch (error) {
    console.error("[DELETE_DOCUMENT]", error);
    return { success: false, error: "Something went wrong. Please try again." };
  }

  revalidatePath("/document");
  redirect("/document");
}
