// Generated by LFG (Let's Fucking Go) — SaaS Autopilot
// 2026-02-27T00:07:12.323Z

import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Reset Password",
};

async function resetPasswordAction(formData: FormData): Promise<void> {
  "use server";

  const { redirect } = await import("next/navigation");
  const email = (formData.get("email") as string)?.trim().toLowerCase();

  if (!email) {
    redirect("/reset-password?error=email_required");
  }

  // Import inline to avoid exposing db to client bundle
  const { db } = await import("@/lib/db");

  const user = await db.user.findUnique({ where: { email } });

  if (user) {
    // Generate a secure token
    const tokenBytes = crypto.getRandomValues(new Uint8Array(32));
    const token = Array.from(tokenBytes)
      .map((b) => b.toString(16).padStart(2, "0"))
      .join("");

    const expires = new Date(Date.now() + 1000 * 60 * 60); // 1 hour

    await db.verificationToken.create({
      data: {
        identifier: email,
        token,
        expires,
      },
    });

    // TODO: send email with reset link
    // The reset link would be: `${process.env.NEXTAUTH_URL}/reset-password/confirm?token=${token}&email=${encodeURIComponent(email)}`
    // Wire up your email provider here (Resend, SendGrid, Nodemailer, etc.)
    console.log(
      `[reset-password] Token for ${email}: ${token} (expires ${expires.toISOString()})`
    );
  }

  // Always redirect to success to prevent email enumeration
  redirect("/reset-password?success=1");
}

export default function ResetPasswordPage({
  searchParams,
}: {
  searchParams: Promise<{ success?: string }>;
}) {
  return (
    <>
      <div className="mb-6">
        <h2 className="text-xl font-semibold text-slate-900">Reset your password</h2>
        <p className="text-sm text-slate-500 mt-1">
          Enter your email and we&apos;ll send you a reset link.
        </p>
      </div>

      <form action={resetPasswordAction} className="space-y-4">
        <div>
          <label
            htmlFor="email"
            className="block text-sm font-medium text-slate-700 mb-1"
          >
            Email address
          </label>
          <input
            id="email"
            name="email"
            type="email"
            autoComplete="email"
            required
            placeholder="you@example.com"
            className="w-full px-3 py-2.5 border border-slate-200 rounded-lg text-sm text-slate-900 placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent transition"
          />
        </div>

        <button
          type="submit"
          className="w-full py-2.5 px-4 bg-indigo-600 hover:bg-indigo-700 text-white text-sm font-medium rounded-lg transition-colors focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"
        >
          Send reset link
        </button>
      </form>

      {/* Success state rendered via server component re-render */}
      <p className="text-center text-sm text-slate-500 mt-6">
        Remember your password?{" "}
        <Link
          href="/login"
          className="text-indigo-600 hover:text-indigo-500 font-medium"
        >
          Sign in
        </Link>
      </p>
    </>
  );
}
